
#define AIRLOCK_MARKER_TAG_MASTER			"[master_tag]"
#define AIRLOCK_MARKER_TAG_SENSOR_CHAMBER		"[master_tag]_sensor_chamber"
#define AIRLOCK_MARKER_TAG_SENSOR_INTERIOR		"[master_tag]_sensor_interior"
#define AIRLOCK_MARKER_TAG_SENSOR_EXTERIOR		"[master_tag]_sensor_exterior"
#define AIRLOCK_MARKER_TAG_DOOR_EXTERIOR	"[master_tag]_door_exterior"
#define AIRLOCK_MARKER_TAG_DOOR_INTERIOR	"[master_tag]_door_interior"
#define AIRLOCK_MARKER_TAG_AIRPUMP_CHAMBER		"[master_tag]_airpump_chamber"
#define AIRLOCK_MARKER_TAG_AIRPUMP_OUT_EXTERNAL	"[master_tag]_pump_out_external"
#define AIRLOCK_MARKER_TAG_AIRPUMP_OUT_INTERNAL	"[master_tag]_pump_out_internal"
