/singleton/synthetic_organ_preset/reactor
	name = "super cool power reactor"
	desc = "It is a mega cool power reactor."

	/// What kind of power reactor this is. Bitfield.
	var/power_supply_type
	/// The amount of power this active reactor generates on a 'tick'.
	var/base_power_generation
	/// The modifier for external charging. Higher on electric supplies.
	var/external_charge_multiplier

/singleton/synthetic_organ_preset/reactor/apply_preset(obj/item/organ/internal/machine/organ)
	. = ..()
	var/obj/item/organ/internal/machine/reactor/reactor = organ
	reactor.base_power_generation = base_power_generation
	reactor.power_supply_type = power_supply_type
	reactor.external_charge_multiplier = external_charge_multiplier

/singleton/synthetic_organ_preset/reactor/electric
	name = "electrical power supply unit"
	desc = "An electrical power supply system for a synthetic. It feeds from external sources."
	icon_state = "ipc_electrical_reactor"

	external_charge_multiplier = 1.5
	base_power_generation = 0
	power_supply_type = POWER_SUPPLY_ELECTRIC

/singleton/synthetic_organ_preset/reactor/kinetic
	name = "kinetic power generator"
	desc = "A simple, but effective power generator that uses motion to generate power."

	external_charge_multiplier = 0.5
	base_power_generation = 5
	power_supply_type = POWER_SUPPLY_KINETIC

/singleton/synthetic_organ_preset/reactor/biological
	name = "catalytic biomass reactor"
	desc = "An advanced, artificial emulation of an organic creature's internal power generation method."
	icon_state = "ipc_bio_reactor"

	external_charge_multiplier = 0.25
	base_power_generation = 15
	power_supply_type = POWER_SUPPLY_BIOLOGICAL

/singleton/synthetic_organ_preset/reactor/biological/apply_preset(obj/item/organ/internal/machine/organ)
	. = ..()
	var/obj/item/organ/internal/machine/reactor/reactor = organ
	reactor.bio_reagents = new(30, reactor)

/singleton/synthetic_organ_preset/reactor/solar
	name = "solar power generator"
	desc = "A complex power generator that harnesses the power generated by lights to power a synthetic."
	icon_state = "ipc_solar_reactor"

	external_charge_multiplier = 0.5
	base_power_generation = 100
	power_supply_type = POWER_SUPPLY_SOLAR
