/singleton/synthetic_organ_preset/reactor
	name = "super cool power reactor"
	desc = "It is a mega cool power reactor."

	/// What kind of power reactor this is. Bitfield.
	var/power_supply_type
	/// The amount of power this active reactor generates on a 'tick'.
	var/base_power_generation
	/// The modifier for external charging. Higher on electric supplies.
	var/external_charge_multiplier

/singleton/synthetic_organ_preset/reactor/apply_preset(obj/item/organ/internal/machine/organ)
	. = ..()
	if(!.)
		return

	var/obj/item/organ/internal/machine/reactor/reactor = organ

/singleton/synthetic_organ_preset/reactor/electric
	name = "electrical power supply unit"
	desc = "An electrical power supply system for a synthetic. It feeds from external sources."

/singleton/synthetic_organ_preset/reactor/kinetic
	name = "kinetic power generator"
	desc = "A simple, but effective power generator that uses motion to generate power."

/singleton/synthetic_organ_preset/reactor/biological
	name = "biological power generator"
	desc = "An advanced artificial emulation of an organic's internal power generation method."

/singleton/synthetic_organ_preset/reactor/solar
	name = "solar power generator"
	desc = "A complex power generator that harnesses the power generated by lights to power a synthetic."
