/**
 * Component used as both a logical proof that "This mob Can Feel Pain" as well as a container for storing pain.
 * Having this component is required for Pain to work, and it provides fast access to other systems to retrieve a mob's pain.
 */
/datum/component/pain_container
	/// Current pain amount stored by this component. Equal to Base + Sources.
	var/pain_total = 0

	/// The base amount of pain stored by this component not including its sources.
	var/pain_base = 0

	/**
	 * The "Upstream" pain container that receives from this container. Only one upstream is allowed, but any number of sources are permitted.
	 */
	var/datum/component/pain_container/upstream

	/// Associated List of all source pain components and the amount of pain they are currently providing.
	var/list/datum/component/pain_container/pain_sources = list()

	/// The amount of pain generated per point of brute damage.
	var/pain_per_brute = 0.7

	/// The amount of pain generated per point of burn damage.
	var/pain_per_burn = 0.8

	/// The amount of pain generated per point of genetic damage.
	var/pain_per_genetic = 0.5

	/// The amount of pain generated per point of toxin damage.
	var/pain_per_toxin = 0.3

	/// The amount of pain generated by the broken condition.
	var/pain_if_broken = 10

	/// The amount of pain generated by the dislocated condition.
	var/pain_if_dislocated = 5

/datum/component/pain_container/Initialize()
	. = ..()


/datum/component/pain_container/proc/recalculate_pain()
	var/pain_total = pain_base
	for(var/datum/component/pain_container/source_comp,value in pain_sources)
		pain_total += value

/datum/component/pain_container/proc/add_pain(var/amount)
	pain_total += amount
	pain_base += amount
	if(upstream)
		upstream.add_pain(upstream.pain_sources[src] - pain_total)
		upstream.pain_sources[src] = pain_total

/datum/component/pain_container/proc/remove_pain(var/amount)
	pain_total -= amount
	pain_base -= amount
	if(upstream)
		upstream.remove_pain(upstream.pain_sources[src] - pain_total)
		upstream.pain_sources[src] = pain_total

/datum/component/pain_container/proc/set_pain(var/amount)
	pain_total = amount
	pain_base = amount
	for(var/datum/component/pain_container/source_comp,value in pain_sources)
		pain_total += value
	if(upstream)
		upstream.add_pain(upstream.pain_sources[src] - pain_total)
		upstream.pain_sources[src] = pain_total

/datum/component/pain_container/Destroy(force)
	. = ..()
	if(upstream)
		upstream.pain_sources.Remove(src)
		upstream.remove_pain(pain_total)
	upstream = null
	if(pain_sources)
		for(var/datum/component/pain_container/key,value in pain_sources)
			key.upstream = null
	pain_sources = null
