#undef LIGHTING_HEIGHT

#undef LIGHTING_ICON

#undef LIGHTING_BASE_MATRIX

#undef LUM_FALLOFF
#undef REMOVE_CORNER
#undef APPLY_CORNER

#undef CALCULATE_CORNER_HEIGHT
#undef APPLY_CORNER_BY_HEIGHT
#undef APPLY_CORNER_SIMPLE
