// the underfloor wiring terminal for the APC
// autogenerated when an APC is placed
// all conduit connects go to this object instead of the APC
// using this solves the problem of having the APC in a wall yet also inside an area

/obj/structure/machinery/power/terminal
	name = "terminal"
	icon_state = "term"
	desc = "It's an underfloor wiring terminal for power equipment."
	level = 1
	plane = FLOOR_PLANE
	layer = WIRE_TERMINAL_LAYER
	var/obj/structure/machinery/power/master = null
	anchored = 1


/obj/structure/machinery/power/terminal/Initialize()
	. = ..()
	AddElement(/datum/element/undertile, TRAIT_T_RAY_VISIBLE)
	RegisterSignal(src, COMSIG_UNDERTILE_UPDATED, PROC_REF(on_undertile_updated))
	update_underfloor_from_turf()
	return

/obj/structure/machinery/power/terminal/Destroy()
	if(master)
		master.disconnect_terminal()
		master = null
	return ..()

/obj/structure/machinery/power/terminal/uses_undertile()
	return TRUE

/obj/structure/machinery/power/terminal/proc/on_undertile_updated()
	SIGNAL_HANDLER
	icon_state = invisibility ? "term-f" : "term"
