//FMJ
#define FMJ_DAMAGE_MULTIPLIER 1.0
#define FMJ_AP_MULTIPLIER 1.0

//JHP
#define JHP_DAMAGE_MULTIPLIER 1.2
#define JHP_AP_MULTIPLIER 0.75

//AP
#define AP_DAMAGE_MULTIPLIER 0.8
#define AP_AP_MULTIPLIER 1.2

//Polymer
#define POLYMER_DAMAGE_MULTIPLIER 0.8
#define POLYMER_AP_MULTIPLIER 1.1
