//citizenship defines
#define CITIZENSHIP_BIESEL "Republic of Biesel"
#define CITIZENSHIP_SOL "Sol Alliance"
#define CITIZENSHIP_COALITION "Coalition of Colonies"
#define CITIZENSHIP_ELYRA "Republic of Elyra"
#define CITIZENSHIP_ERIDANI "Eridani Federation"
#define CITIZENSHIP_DOMINIA "Empire of Dominia"

#define CITIZENSHIP_IZWESKI "Izweski Hegemony"

#define CITIZENSHIP_NRALAKK "Nralakk Federation"
#define CITIZENSHIP_EUM "Co-Operative Territories of EUM"

#define CITIZENSHIP_PRA "People's Republic of Adhomai"
#define CITIZENSHIP_DPRA "Democratic People's Republic of Adhomai"
#define CITIZENSHIP_NKA "New Kingdom of Adhomai"
#define CITIZENSHIP_FREE_COUNCIL "Free Tajaran Council"

#define CITIZENSHIP_ZORA "Zo'ra Hive"
#define CITIZENSHIP_KLAX "K'lax Hive"
#define CITIZENSHIP_CTHUR "C'thur Hive"

#define CITIZENSHIP_NONE "None"
#define CITIZENSHIP_GOLDEN "Golden Deep"

//religion defines
#define RELIGION_NONE "None"
#define RELIGION_OTHER "Other"
#define RELIGION_CHRISTIANITY "Christianity"
#define RELIGION_ISLAM "Islam"
#define RELIGION_JUDAISM "Judaism"
#define RELIGION_HINDU "Hinduism"
#define RELIGION_BUDDHISM "Buddhism"
#define RELIGION_SHINTO "Shinto"
#define RELIGION_MOROZ "Moroz Holy Tribunal"
#define RELIGION_TRINARY "Trinary Perfection"
#define RELIGION_SCARAB "Scarab Folk Beliefs"
#define RELIGION_TAOISM "Taoism"
#define RELIGION_LUCEISM "Luceism"

#define RELIGION_THAKH "Th'akh"
#define RELIGION_SKAKH "Sk'akh"
#define RELIGION_AUTAKH "Aut'akh"
#define RELIGION_SIAKH "Si'akh"

#define RELIGION_QEBLAK "Qeblak"
#define RELIGION_WEISHII "Weishii"
#define RELIGION_SUURKA "Suur'ka"
#define RELIGION_KIRGUL "Kir'gul"

#define RELIGION_TWINSUNS "S'rendarr and Messa"
#define RELIGION_MATAKE "Ma'ta'ke"
#define RELIGION_RASKARA "Raskariim"

#define RELIGION_HIVEPANTHEON "Hive Pantheon"
#define RELIGION_PREIMMINENNCE "Preimminennce"
#define RELIGION_PILOTDREAM "Pilot Dream"

#define RELIGION_ETERNAL "The Eternal"
#define RELIGION_KSSHR "Ksshr"
#define RELIGION_SHRKH "Shrkh"

//accent defines

#define ACCENT_CETI "Biesellite"
#define ACCENT_COC "Frontiersfolk"
#define ACCENT_ELYRA "Elyran"
#define ACCENT_ERIDANI "Eridanian"
#define ACCENT_ERIDANIREINSTATED "Reinstated Dreg"
#define ACCENT_ERIDANIDREG "Eridanian Dreg"
#define ACCENT_SOL "Solarian"
#define ACCENT_SCARAB "Scarab Fleets"
#define ACCENT_SILVERSUN_ORIGINAL "Silversun Original"
#define ACCENT_SILVERSUN_EXPATRIATE "Silversun Expatriate"
#define ACCENT_PHONG "New Hai Phongese"
#define ACCENT_MARTIAN "Martian"
#define ACCENT_KONYAN "Konyanger"
#define ACCENT_LUNA "Lunan"
#define ACCENT_GIBSON_OVAN "New Gibson Ovanstad"
#define ACCENT_GIBSON_UNDIR "New Gibson Undirstad"
#define ACCENT_HIMEO "Himean"
#define ACCENT_VYSOKA "Vysokan"
#define ACCENT_VENUS "Venusian Cytherean"
#define ACCENT_VENUSJIN "Venusian Jintarian"
#define ACCENT_DOMINIA_HIGH "High Morozi"
#define ACCENT_DOMINIA_VULGAR "Vulgar Morozi"
#define ACCENT_JUPITER "Jovian"
#define ACCENT_CALLISTO "Callistean"
#define ACCENT_EUROPA "Europan"
#define ACCENT_EARTH "Earther"
#define ACCENT_NCF "Non-Coalition Frontier"
#define ACCENT_FISANDUH "Fisanduhian"
#define ACCENT_GADPATHUR "Gadpathurian"
#define ACCENT_PLUTO "Plutonian"
#define ACCENT_ASSUNZIONE "Assunzionii"
#define ACCENT_VISEGRAD "Visegradi"
#define ACCENT_VALKYRIE "Valkyrian"
#define ACCENT_MICTLAN "Mictlanian"
#define ACCENT_PERSEPOLIS "Persepolis"
#define ACCENT_MEDINA "Medina"
#define ACCENT_AEMAQ "Aemaq"
#define ACCENT_NEWSUEZ "New Suez"
#define ACCENT_DAMASCUS "Damascus II"
#define ACCENT_ANTILLIA "Port Antillia"
#define ACCENT_XANU "Xanu"
#define ACCENT_SANCOLETTE "San Colette"

#define ACCENT_REPUBICLANSIIK "Republican Siik'maas"
#define ACCENT_NAZIRASIIK "Nazira Siik'maas"
#define ACCENT_CREVAN "Crevan Creole"
#define ACCENT_DASNRRASIIK "Das'nrra Siik'maas"
#define ACCENT_HIGHHARRSIIK "High-Harr'masir Siik'maas"
#define ACCENT_LOWHARRSIIK "Lower-Harr'masir Siik'maas"
#define ACCENT_AMOHDASIIK "Amohdan Siik'maas"
#define ACCENT_RURALDELVAHHI "Rural Delvahhi"
#define ACCENT_NOMADDELVAHHI "Nomadic Delvahhi"
#define ACCENT_OLDYASSA "Old Ya'ssa"
#define ACCENT_NORTHRASNRR "Northern Ras'nrr Siik'maas"
#define ACCENT_DINAKK "Din'akk Mountains Siik'maas"
#define ACCENT_HARRNRRI "Harr'nrri Siik'mas"
#define ACCENT_ZARRJIRI "Zarr'jiri Siik'mas"

#define ACCENT_HEGEMON_NOBLE "Noble Hegemonic"
#define ACCENT_HEGEMON_PEASANT "Peasant Hegemonic"
#define ACCENT_TRAD_NOBLE "Noble Traditional"
#define ACCENT_TRAD_PEASANT "Peasant Traditional"
#define ACCENT_WASTELAND "Deep Wastelander"

#define ACCENT_SKRELL "Standard Nral'Malic"
#define ACCENT_HOMEWORLD "Qerrbalak"
#define ACCENT_QERRMALIC "Qerr'Malic"
#define ACCENT_ALIOSE "Aliose"
#define ACCENT_AWEIJI "Aweiji"
#define ACCENT_TRAVERSE "Traverse"
#define ACCENT_GENNER "Generational Ship"
#define ACCENT_SKRELLSOL "Solarian Skrell Standard"
#define ACCENT_SKRELLCOC "Coalition Skrell Standard"
#define ACCENT_SKRELLCETI "Biesellite Skrell Standard"
#define ACCENT_SROM "Inner Voice"
#define ACCENT_TATTUQIG "Tattuqig"

#define ACCENT_ROOTSONG "Rootsong"
#define ACCENT_VOIDSONG "Voidsong"

#define ACCENT_TTS "Text-to-Speech"

#define ACCENT_BLUESPACE "Bluespace"

#define ACCENT_ZORA "Zo'rane"
#define ACCENT_KLAX "K'laxane"
#define ACCENT_CTHUR "C'thuric"
#define ACCENT_LIIDRA "Lii'draic"

#define ACCENTS_ALL_IPC_SOL list(ACCENT_SOL, ACCENT_EARTH, ACCENT_SILVERSUN_ORIGINAL, ACCENT_SILVERSUN_EXPATRIATE, ACCENT_VENUS, ACCENT_VENUSJIN, ACCENT_MARTIAN, ACCENT_JUPITER, ACCENT_CALLISTO, ACCENT_EUROPA, ACCENT_PHONG, ACCENT_ERIDANI, ACCENT_PLUTO, ACCENT_MICTLAN, ACCENT_KONYAN, ACCENT_LUNA, ACCENT_TTS)
#define ACCENTS_ALL_IPC list(ACCENT_CETI, ACCENT_TTS, ACCENT_XANU, ACCENT_COC, ACCENT_ELYRA, ACCENT_ERIDANI, ACCENT_ERIDANIDREG, ACCENT_ERIDANIREINSTATED, ACCENT_SOL, ACCENT_SILVERSUN_EXPATRIATE, ACCENT_SILVERSUN_ORIGINAL, ACCENT_PHONG, ACCENT_MARTIAN, ACCENT_KONYAN, ACCENT_LUNA, ACCENT_GIBSON_OVAN, ACCENT_GIBSON_UNDIR, ACCENT_HIMEO, ACCENT_VYSOKA, ACCENT_VENUS, ACCENT_VENUSJIN, ACCENT_JUPITER, ACCENT_CALLISTO, ACCENT_EUROPA, ACCENT_EARTH, ACCENT_NCF, ACCENT_PLUTO, ACCENT_ASSUNZIONE, ACCENT_VISEGRAD, ACCENT_SANCOLETTE, ACCENT_VALKYRIE, ACCENT_MICTLAN, ACCENT_PERSEPOLIS, ACCENT_MEDINA, ACCENT_NEWSUEZ, ACCENT_AEMAQ, ACCENT_DAMASCUS)
#define RELIGIONS_ALL_IPC list(RELIGION_NONE, RELIGION_CHRISTIANITY, RELIGION_ISLAM, RELIGION_BUDDHISM, RELIGION_HINDU, RELIGION_TAOISM, RELIGION_JUDAISM, RELIGION_OTHER, RELIGION_TRINARY, RELIGION_SCARAB, RELIGION_LUCEISM, RELIGION_SHINTO)