CREATE TABLE `ss13_news` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`author` VARCHAR(255) NOT NULL COLLATE 'utf8_bin',
	`channel` VARCHAR(255) NOT NULL COLLATE 'utf8_bin',
	`body` TEXT NOT NULL COLLATE 'utf8_bin',
	`created_by` VARCHAR(255) NOT NULL COLLATE 'utf8_bin',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;