CREATE TABLE `ss13_item_worths` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`path` VARCHAR(255) NOT NULL COLLATE 'utf8_bin',
	`value` INT(10) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `path` (`path`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;