--
-- Create the Documents database.
--

CREATE TABLE `ss13_documents` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL COLLATE 'utf8_bin',
	`title` VARCHAR(26) NOT NULL COLLATE 'utf8_bin',
	`chance` FLOAT UNSIGNED NOT NULL DEFAULT '1',
	`content` VARCHAR(3072) NOT NULL COLLATE 'utf8_bin',
	`tags` JSON NOT NULL COLLATE 'utf8_bin',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE INDEX `name` (`name`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;
