#define ACCESSORY_SLOT_GENERIC			"decor"
#define ACCESSORY_SLOT_UTILITY			"utility"
#define ACCESSORY_SLOT_UTILITY_MINOR	"minor utility"
#define ACCESSORY_SLOT_CAPE				"cape"
#define ACCESSORY_SLOT_ARMBAND			"armband"
#define ACCESSORY_SLOT_ARMOR_PLATE		"armor plate"
#define ACCESSORY_SLOT_LEG_GUARDS		"leg guards"
#define ACCESSORY_SLOT_ARM_GUARDS		"arm guards"
#define ACCESSORY_SLOT_ARMOR_PIN		"armor pin"
#define ACCESSORY_SLOT_ARMOR_POCKETS 	"armor pockets"
#define ACCESSORY_SLOT_HEAD             "head"
