//citizenship defines
#define CITIZENSHIP_BIESEL "Republic of Biesel"
#define CITIZENSHIP_SOL "Sol Alliance"
#define CITIZENSHIP_COALITION "Coalition of Colonies"
#define CITIZENSHIP_ELYRA "Republic of Elyra"
#define CITIZENSHIP_ELYRA_NCP "Elyran Non-Citizen Person"
#define CITIZENSHIP_ERIDANI "Eridani Federation"
#define CITIZENSHIP_DOMINIA "Empire of Dominia"

#define CITIZENSHIP_IZWESKI "Izweski Hegemony"

#define CITIZENSHIP_NRALAKK "Nralakk Federation"
#define CITIZENSHIP_EUM "Co-Operative Territories of EUM"

#define CITIZENSHIP_PRA "People's Republic of Adhomai"
#define CITIZENSHIP_DPRA "Democratic People's Republic of Adhomai"
#define CITIZENSHIP_NKA "New Kingdom of Adhomai"
#define CITIZENSHIP_FREE_COUNCIL "Free Tajaran Council"

#define CITIZENSHIP_ZORA "Zo'ra Hive"
#define CITIZENSHIP_KLAX "K'lax Hive"
#define CITIZENSHIP_CTHUR "C'thur Hive"

#define CITIZENSHIP_NONE "None"
#define CITIZENSHIP_GOLDEN "Golden Deep"

//religion defines
#define RELIGION_NONE "None"
#define RELIGION_OTHER "Other"
#define RELIGION_CHRISTIANITY "Christianity"
#define RELIGION_ISLAM "Islam"
#define RELIGION_JUDAISM "Judaism"
#define RELIGION_HINDU "Hinduism"
#define RELIGION_BUDDHISM "Buddhism"
#define RELIGION_SHINTO "Shinto"
#define RELIGION_MOROZ "Moroz Holy Tribunal"
#define RELIGION_TRINARY "Trinary Perfection"
#define RELIGION_SCARAB "Scarab Folk Beliefs"
#define RELIGION_TAOISM "Taoism"
#define RELIGION_LUCEISM "Luceism"
#define RELIGION_SIKHISM "Sikhism"
#define RELIGION_STOLITISM "Vysokan Stolitism"

#define RELIGION_THAKH "Th'akh"
#define RELIGION_SKAKH "Sk'akh"
#define RELIGION_AUTAKH "Aut'akh"
#define RELIGION_SIAKH "Si'akh"

#define RELIGION_QEBLAK "Qeblak"
#define RELIGION_WEISHII "Weishii"
#define RELIGION_SUURKA "Suur'ka"
#define RELIGION_KIRGUL "Kir'gul"

#define RELIGION_TWINSUNS "S'rendarr and Messa"
#define RELIGION_MATAKE "Ma'ta'ke"
#define RELIGION_RASKARA "Raskariim"

#define RELIGION_HIVEPANTHEON "Hive Pantheon"
#define RELIGION_PREIMMINENNCE "Preimminennce"
#define RELIGION_PILOTDREAM "Pilot Dream"

#define RELIGION_ETERNAL "Orthodox Eternal"
#define RELIGION_ETERNAL_ICHOR "Ichor Eternal"
#define RELIGION_ETERNAL_IRON "Iron Eternal"
#define RELIGION_MADA "Maraka"
#define RELIGION_GLEANERS "Lights Accord"

//accent defines

#define ACCENT_CETI "Biesellite"
#define ACCENT_COC "Frontiersfolk"
#define ACCENT_ELYRA "Elyran"
#define ACCENT_ERIDANI "Eridanian"
#define ACCENT_ERIDANIREINSTATED "Reinstated Dreg"
#define ACCENT_ERIDANIDREG "Eridanian Dreg"
#define ACCENT_SOL "Solarian"
#define ACCENT_SCARAB "Scarab Fleets"
#define ACCENT_SILVERSUN_ORIGINAL "Silversun Original"
#define ACCENT_SILVERSUN_EXPATRIATE "Silversun Expatriate"
#define ACCENT_PHONG "New Hai Phongese"
#define ACCENT_MARTIAN "Martian"
#define ACCENT_KONYAN "Konyanger"
#define ACCENT_LUNA "Lunan"
#define ACCENT_GIBSON_OVAN "New Gibson Ovanstad"
#define ACCENT_GIBSON_UNDIR "New Gibson Undirstad"
#define ACCENT_HIMEO "Himean"
#define ACCENT_VYSOKA "Vysokan"
#define ACCENT_VENUS "Venusian Cytherean"
#define ACCENT_VENUSJIN "Venusian Jintarian"
#define ACCENT_DOMINIA_HIGH "High Morozi"
#define ACCENT_DOMINIA_VULGAR "Vulgar Morozi"
#define ACCENT_DOMINIA_FRONTIER "Imperial Frontier"
#define ACCENT_DOMINIA_NOVIJADRAN "Novi Jadranic"
#define ACCENT_DOMINIA_LYODII "Lyodii"
#define ACCENT_DOMINIA_SUNREACH "Sun Reach"
#define ACCENT_JUPITER "Jovian"
#define ACCENT_CALLISTO "Callistean"
#define ACCENT_EUROPA "Europan"
#define ACCENT_EARTH "Earther"
#define ACCENT_NCF "Non-Coalition Frontier"
#define ACCENT_FISANDUH "Fisanduhian"
#define ACCENT_GADPATHUR "Gadpathurian"
#define ACCENT_PLUTO "Plutonian"
#define ACCENT_ASSUNZIONE "Assunzionii"
#define ACCENT_VISEGRAD "Visegradi"
#define ACCENT_VALKYRIE "Valkyrian"
#define ACCENT_MICTLAN "Mictlanian"
#define ACCENT_PERSEPOLIS "Persepolis"
#define ACCENT_MEDINA "Medina"
#define ACCENT_AEMAQ "Aemaq"
#define ACCENT_NEWSUEZ "New Suez"
#define ACCENT_DAMASCUS "Damascus II"
#define ACCENT_BURSA "Bursa"
#define ACCENT_ANTILLIA "Port Antillia"
#define ACCENT_XANU "Xanu"
#define ACCENT_SANCOLETTE "San Colette"
#define ACCENT_OREPIT "Native Orepitter"
#define ACCENT_PROVIDENCE "Providence Trinarist"
#define ACCENT_BURZSIA "Burzsia"
#define ACCENT_GALATEA "Galatean"
#define ACCENT_TSUKUYOMI "Tsukuyomian"
#define ACCENT_EMPYREAN "Empyrean"
#define ACCENT_SVAROG "Svarogite"

#define ACCENT_REPUBICLANSIIK "Republican Siik'maas"
#define ACCENT_NAZIRASIIK "Nazira Siik'maas"
#define ACCENT_CREVAN "Crevan Creole"
#define ACCENT_DASNRRASIIK "Das'nrra Siik'maas"
#define ACCENT_HIGHHARRSIIK "High-Harr'masir Siik'maas"
#define ACCENT_LOWHARRSIIK "Lower-Harr'masir Siik'maas"
#define ACCENT_AMOHDASIIK "Amohdan Siik'maas"
#define ACCENT_RURALDELVAHHI "Rural Delvahhi"
#define ACCENT_NOMADDELVAHHI "Nomadic Delvahhi"
#define ACCENT_OLDYASSA "Old Ya'ssa"
#define ACCENT_NEWYASSA "New Ya'ssa"
#define ACCENT_NORTHRASNRR "Northern Ras'nrr Siik'maas"
#define ACCENT_DINAKK "Din'akk Mountains Siik'maas"
#define ACCENT_HARRNRRI "Harr'nrri Siik'mas"
#define ACCENT_ZARRJIRI "Zarr'jiri Siik'mas"

#define ACCENT_HEARTLAND_NOBLE "Izweski Heartland Noble"
#define ACCENT_HEARTLAND_PEASANT "Izweski Heartland Peasant"
#define ACCENT_TRAD_NOBLE "Noble Traditional"
#define ACCENT_TRAD_PEASANT "Peasant Traditional"
#define ACCENT_WASTELAND "Deep Wastelander"
#define ACCENT_AUTAKH "Aut'akh Dialect"
#define ACCENT_QUEENDOM "Queendom Dialect"
#define ACCENT_TZA_PEASANT "Tza Prairie Peasant"
#define ACCENT_TZA_NOBLE "Tza Prairie Noble"
#define ACCENT_SOUTHLANDS_PEASANT "Southlands Peasant"
#define ACCENT_SOUTHLANDS_NOBLE "Southlands Noble"
#define ACCENT_BROKEN_PEASANT "Broken Coalition Peasant"
#define ACCENT_BROKEN_NOBLE "Broken Coalition Noble"
#define ACCENT_UNATHI_SPACER "Spacer"
#define ACCENT_HAZANA "Hazana"
#define ACCENT_TORN "Torn Cities"
#define ACCENT_ZAZ_LOW "Zazalai Mountains Peasant"
#define ACCENT_ZAZ_HIGH "Zazalai Mountains Noble"
#define ACCENT_OUEREA "Ouerea"

#define ACCENT_SKRELL "Standard Nral'Malic"
#define ACCENT_HOMEWORLD "Qerrbalak"
#define ACCENT_QERRMALIC "Qerr'Malic"
#define ACCENT_ALIOSE "Aliose"
#define ACCENT_AWEIJI "Aweiji"
#define ACCENT_TRAVERSE "Traverse"
#define ACCENT_GENNER "Generational Ship"
#define ACCENT_SKRELLSOL "Solarian Skrell Standard"
#define ACCENT_SKRELLCOC "Coalition Skrell Standard"
#define ACCENT_SKRELLCETI "Biesellite Skrell Standard"
#define ACCENT_SKRELLEUM "Nral'Daaq"
#define ACCENT_SROM "Inner Voice"
#define ACCENT_TATTUQIG "Tattuqig"

#define ACCENT_ROOTSONG "Rootsong"
#define ACCENT_VOIDSONG "Voidsong"
#define ACCENT_ANCIENTSONG "Ancientsong"
#define ACCENT_CRIMSONSONG "Crimsonsong"
#define ACCENT_IRONSONG "Ironsong"
#define ACCENT_SANDSONG "Sandsong"
#define ACCENT_WASTESONG "Wastesong"
#define ACCENT_WAVESONG "Wavesong"
#define ACCENT_SUNKENSONG "Sunkensong"
#define ACCENT_STARSONG "Starsong"
#define ACCENT_XRIMSONG "Xrimsong"
#define ACCENT_PESTSONG "Pestsong"
#define ACCENT_MEADOWSONG "Meadowsong"
#define ACCENT_LABOURSONG "Laboursong"

#define ACCENT_TTS "Text-to-Speech"

#define ACCENT_BLUESPACE "Bluespace"

#define ACCENT_ZORA "Zo'rane"
#define ACCENT_KLAX "K'laxane"
#define ACCENT_CTHUR "C'thuric"
#define ACCENT_LIIDRA "Lii'draic"

#define ACCENTS_ALL_IPC_SOL list(ACCENT_SOL, ACCENT_EARTH, ACCENT_SILVERSUN_ORIGINAL, ACCENT_SILVERSUN_EXPATRIATE, ACCENT_VENUS, ACCENT_VENUSJIN, ACCENT_MARTIAN, ACCENT_JUPITER, ACCENT_CALLISTO, ACCENT_EUROPA, ACCENT_PHONG, ACCENT_ERIDANI, ACCENT_PLUTO, ACCENT_VISEGRAD, ACCENT_MICTLAN, ACCENT_KONYAN, ACCENT_LUNA, ACCENT_SANCOLETTE, ACCENT_TTS)
#define ACCENTS_ALL_IPC list(ACCENT_CETI, ACCENT_TTS, ACCENT_XANU, ACCENT_COC, ACCENT_ELYRA, ACCENT_ERIDANI, ACCENT_ERIDANIDREG, ACCENT_ERIDANIREINSTATED, ACCENT_SOL, ACCENT_SILVERSUN_EXPATRIATE, ACCENT_SILVERSUN_ORIGINAL, ACCENT_PHONG, ACCENT_MARTIAN, ACCENT_KONYAN, ACCENT_LUNA, ACCENT_GIBSON_OVAN, ACCENT_GIBSON_UNDIR, ACCENT_HIMEO, ACCENT_VYSOKA, ACCENT_VENUS, ACCENT_VENUSJIN, ACCENT_JUPITER, ACCENT_CALLISTO, ACCENT_EUROPA, ACCENT_EARTH, ACCENT_NCF, ACCENT_PLUTO, ACCENT_ASSUNZIONE, ACCENT_VISEGRAD, ACCENT_SANCOLETTE, ACCENT_VALKYRIE, ACCENT_MICTLAN, ACCENT_PERSEPOLIS, ACCENT_MEDINA, ACCENT_NEWSUEZ, ACCENT_AEMAQ, ACCENT_DAMASCUS)
#define RELIGIONS_ALL_IPC list(RELIGION_NONE, RELIGION_CHRISTIANITY, RELIGION_ISLAM, RELIGION_BUDDHISM, RELIGION_HINDU, RELIGION_TAOISM, RELIGION_JUDAISM, RELIGION_OTHER, RELIGION_TRINARY, RELIGION_SCARAB, RELIGION_LUCEISM, RELIGION_SHINTO)

#define RELIGIONS_BIESEL list(RELIGION_NONE, RELIGION_CHRISTIANITY, RELIGION_ISLAM, RELIGION_BUDDHISM, RELIGION_SHINTO, RELIGION_HINDU, RELIGION_TAOISM, RELIGION_JUDAISM, RELIGION_SIKHISM, RELIGION_OTHER, RELIGION_TRINARY)
#define CITIZENSHIPS_BIESEL list(CITIZENSHIP_BIESEL, CITIZENSHIP_ERIDANI, CITIZENSHIP_COALITION)

#define RELIGIONS_COALITION list(RELIGION_NONE, RELIGION_CHRISTIANITY, RELIGION_ISLAM, RELIGION_BUDDHISM, RELIGION_SHINTO, RELIGION_HINDU, RELIGION_TAOISM, RELIGION_JUDAISM, RELIGION_SIKHISM, RELIGION_OTHER, RELIGION_TRINARY)
#define RELIGIONS_COALITION_ALL list(RELIGION_NONE, RELIGION_CHRISTIANITY, RELIGION_ISLAM, RELIGION_BUDDHISM, RELIGION_SHINTO, RELIGION_HINDU, RELIGION_TAOISM, RELIGION_JUDAISM, RELIGION_SIKHISM, RELIGION_OTHER, RELIGION_TRINARY, RELIGION_SCARAB, RELIGION_MOROZ)
#define CITIZENSHIPS_COALITION list(CITIZENSHIP_COALITION, CITIZENSHIP_BIESEL)

#define RELIGIONS_ELYRA list(RELIGION_NONE, RELIGION_CHRISTIANITY, RELIGION_ISLAM, RELIGION_SHINTO, RELIGION_BUDDHISM, RELIGION_HINDU, RELIGION_TAOISM, RELIGION_JUDAISM, RELIGION_SIKHISM, RELIGION_OTHER)

#define RELIGIONS_SOLARIAN list(RELIGION_NONE, RELIGION_CHRISTIANITY, RELIGION_ISLAM, RELIGION_SHINTO, RELIGION_BUDDHISM, RELIGION_HINDU, RELIGION_TAOISM, RELIGION_JUDAISM, RELIGION_SIKHISM, RELIGION_OTHER, RELIGION_TRINARY)
#define CITIZENSHIPS_SOLARIAN list(CITIZENSHIP_SOL, CITIZENSHIP_BIESEL, CITIZENSHIP_ERIDANI, CITIZENSHIP_COALITION)

#define CITIZENSHIPS_NRALAKK list(CITIZENSHIP_NRALAKK, CITIZENSHIP_EUM)
#define RELIGIONS_NRALAKK list(RELIGION_QEBLAK, RELIGION_WEISHII, RELIGION_SUURKA, RELIGION_KIRGUL, RELIGION_OTHER, RELIGION_NONE)

#define RELIGIONS_ADHOMAI list(RELIGION_TWINSUNS, RELIGION_MATAKE, RELIGION_RASKARA, RELIGION_NONE, RELIGION_OTHER)
#define CITIZENSHIPS_ADHOMAI list(CITIZENSHIP_PRA, CITIZENSHIP_DPRA, CITIZENSHIP_NKA)

#define CITIZENSHIPS_DOMINIA list(CITIZENSHIP_DOMINIA, CITIZENSHIP_COALITION, CITIZENSHIP_BIESEL)
