#define COMSIG_BASENAME_RENAME "base_name_rename"
#define COMSIG_BASENAME_SETNAME "base_name_setname"
#define ARMED_COMBAT_SKILL_COMPONENT /datum/component/skill/armed_combat
#define FIREARMS_SKILL_COMPONENT /datum/component/skill/firearms
#define UNARMED_COMBAT_SKILL_COMPONENT /datum/component/skill/unarmed_combat
#define PILOT_MECHS_SKILL_COMPONENT /datum/component/skill/pilot_mechs
#define PILOT_SPACECRAFT_SKILL_COMPONENT /datum/component/skill/pilot_spacecraft
#define ROBOTICS_SKILL_COMPONENT /datum/component/skill/robotics
#define ARCHAOLOGY_SKILL_COMPONENT /datum/component/skill/archaology
#define RESEARCH_SKILL_COMPONENT /datum/component/skill/research
#define XENOBIOLOGY_SKILL_COMPONENT /datum/component/skill/xenobiology
#define XENOBOTANY_SKILL_COMPONENT /datum/component/skill/xenobotany
#define BARTENDING_SKILL_COMPONENT /datum/component/skill/bartending
#define COOKING_SKILL_COMPONENT /datum/component/skill/cooking
#define ENTERTAINING_SKILL_COMPONENT /datum/component/skill/entertaining
#define GARDENING_SKILL_COMPONENT /datum/component/skill/gardening
#define MEDICINE_SKILL_COMPONENT /datum/component/skill/medicine
#define SKILL_COMPONENT /datum/component/skill
#define MORALE_COMPONENT /datum/component/morale
#define ELECTRICAL_ENGINEERING_SKILL_COMPONENT /datum/component/skill/electrical_engineering
#define MECHANICAL_ENGINEERING_SKILL_COMPONENT /datum/component/skill/electrical_engineering
#define ATMOSPHERICS_SYSTEMS_SKILL_COMPONENT /datum/component/skill/atmospherics_systems
#define REACTOR_SYSTEMS_SKILL_COMPONENT /datum/component/skill/reactor_systems
#define LEADERSHIP_SKILL_COMPONENT /datum/component/skill/leadership
#define ANATOMY_SKILL_COMPONENT /datum/component/skill/anatomy
#define FORENSICS_SKILL_COMPONENT /datum/component/skill/forensics
#define PHARMACOLOGY_SKILL_COMPONENT /datum/component/skill/pharmacology
#define SURGERY_SKILL_COMPONENT /datum/component/skill/surgery
