#define EVIDENCE_TYPE_BLOOD "Blood"
#define EVIDENCE_TYPE_GSR "Gunshot Residue"
#define EVIDENCE_TYPE_SALIVA "Saliva"
#define EVIDENCE_TYPE_ADDITIONAL "Additional"

#define MICROSCOPE_FIBER BITFLAG(0)
#define MICROSCOPE_PRINTS BITFLAG(1)
#define MICROSCOPE_GSR BITFLAG(2)
#define MICROSCOPE_CELLS BITFLAG(3)
#define MICROSCOPE_ALL MICROSCOPE_FIBER | MICROSCOPE_PRINTS | MICROSCOPE_GSR | MICROSCOPE_CELLS
