// Human Overlays Indexes //
// Layer 1 intentionally left empty.
#define FIRE_LAYER_LOWER        2
#define MUTATIONS_LAYER         3
#define SURGERY_LAYER           4
#define UNDERWEAR_LAYER         5
#define TAIL_SOUTH_LAYER        6
#define TAIL_SOUTH_ACC_LAYER    7
#define SHOES_LAYER_ALT         8
#define WRISTS_LAYER_UNDER      9
#define UNIFORM_LAYER           10
#define MOB_DAMAGE_LAYER        11
#define ID_LAYER                12
#define BANDAGE_LAYER           13
#define SHOES_LAYER             14
#define GLOVES_LAYER            15
#define BELT_LAYER              16
#define WRISTS_LAYER_UNIFORM    17
#define SUIT_LAYER              18
#define ID_LAYER_ALT            19
#define TAIL_NORTH_LAYER        20
#define TAIL_NORTH_ACC_LAYER    21
#define HAIR_LAYER_ALT          22
#define HAIR_LAYER_ALT_EMISSIVE 23
#define GLASSES_LAYER           24
#define BELT_LAYER_ALT          25
#define SUIT_STORE_LAYER        26
#define BACK_LAYER              27
#define HAIR_LAYER              28
#define HAIR_LAYER_EMISSIVE     29
#define GLASSES_LAYER_ALT       30
#define L_EAR_LAYER             31
#define R_EAR_LAYER             32
#define FACEMASK_LAYER          33
#define HEAD_LAYER              34
#define GLASSES_LAYER_OVER      35
#define COLLAR_LAYER            36
#define WRISTS_LAYER_OVER       37
#define HANDCUFF_LAYER          38
#define LEGCUFF_LAYER           39
#define L_HAND_LAYER            40
#define R_HAND_LAYER            41
#define FIRE_LAYER_UPPER        42
#define TOTAL_LAYERS            42
////////////////////////////
