// Human Overlays Indexes //
// Layer 1 intentionally left empty.
#define FIRE_LAYER_LOWER      2
#define MUTATIONS_LAYER       3
#define SURGERY_LAYER         4
#define UNDERWEAR_LAYER       5
#define TAIL_SOUTH_LAYER      6
#define TAIL_SOUTH_ACC_LAYER  7
#define SHOES_LAYER_ALT       8
#define UNIFORM_LAYER         9
#define DAMAGE_LAYER          10
#define ID_LAYER              11
#define BANDAGE_LAYER         12
#define SHOES_LAYER           13
#define GLOVES_LAYER          14
#define BELT_LAYER            15
#define WRISTS_LAYER_ALT      16
#define SUIT_LAYER            17
#define ID_LAYER_ALT          18
#define TAIL_NORTH_LAYER      19
#define TAIL_NORTH_ACC_LAYER  20
#define HAIR_LAYER_ALT        21
#define GLASSES_LAYER         22
#define BELT_LAYER_ALT        23
#define SUIT_STORE_LAYER      24
#define BACK_LAYER            25
#define HAIR_LAYER            26
#define GLASSES_LAYER_ALT     27
#define L_EAR_LAYER           28
#define R_EAR_LAYER           29
#define FACEMASK_LAYER        30
#define HEAD_LAYER            31
#define GLASSES_LAYER_OVER    32
#define COLLAR_LAYER          33
#define HANDCUFF_LAYER        34
#define LEGCUFF_LAYER         35
#define L_HAND_LAYER          36
#define R_HAND_LAYER          37
#define WRISTS_LAYER          38
#define FIRE_LAYER_UPPER      39
#define TOTAL_LAYERS          39
////////////////////////////
