#define SS_INIT_JOBS				8
#define SS_INIT_AREA				7
#define SS_INIT_PIPENET				6
#define SS_INIT_ATMOS				5
#define SS_INIT_PARALLAX			4
#define SS_INIT_LIGHTING			3
#define SS_INIT_CARGO 				2
#define SS_INIT_MISC				1
#define SS_INIT_TICKER 				0
