// Metals, glasses, rocks, and crystals.
#define MATERIAL_PLASTIC                    "plastic"
#define MATERIAL_PLASTIC_HOLO               "holoplastic"
#define MATERIAL_PLASTEEL                   "plasteel"
#define MATERIAL_STEEL                      "steel"
#define MATERIAL_GLASS                      "glass"
#define MATERIAL_GLASS_REINFORCED           "reinforced glass"
#define MATERIAL_GLASS_WIRED                "wired glass"
#define MATERIAL_GLASS_PHORON               "borosilicate glass"
#define MATERIAL_GLASS_REINFORCED_PHORON    "reinforced borosilicate glass"
#define MATERIAL_GOLD                       "gold"
#define MATERIAL_SILVER                     "silver"
#define MATERIAL_DIAMOND                    "diamond"
#define MATERIAL_PHORON                     "phoron"
#define MATERIAL_URANIUM                    "uranium"
#define MATERIAL_SANDSTONE                  "sandstone"
#define MATERIAL_CONCRETE                   "concrete"
#define MATERIAL_IRON                       "iron"
#define MATERIAL_PLATINUM                   "platinum"
#define MATERIAL_BRONZE                     "bronze"
#define MATERIAL_OSMIUM                     "osmium"
#define MATERIAL_MARBLE                     "marble"
#define MATERIAL_CULT                       "cult"
#define MATERIAL_CULT_REINFORCED            "cult_reinforced"
#define MATERIAL_TITANIUM                   "titanium"
#define MATERIAL_SAND                       "sand"
#define MATERIAL_DIONA                      "biomass"
#define MATERIAL_VAURCA                     "alien biomass"
#define MATERIAL_TRITIUM                    "tritium"
#define MATERIAL_HYDROGEN_METALLIC          "mhydrogen"
#define MATERIAL_ELEVATOR                   "elevatorium"
#define MATERIAL_SHUTTLE                    "shuttle"
#define MATERIAL_SHUTTLE_SKRELL             "skrell"
#define MATERIAL_RUST                       "rust"
#define MATERIAL_CARDBOARD                  "cardboard"
#define MATERIAL_GRAPHITE                   "graphite"
#define MATERIAL_DEUTERIUM					"deuterium"
#define MATERIAL_SUPERMATTER				"supermatter"

// Leathers and related.
#define MATERIAL_RESIN                   "resin"
#define MATERIAL_LEATHER                 "leather"
#define MATERIAL_LEATHER_FINE            "fine leather"
#define MATERIAL_BONE                    "bone"
#define MATERIAL_BONE_CURSED             "cursed bone"
#define MATERIAL_HIDE                    "hide"
#define MATERIAL_HIDE_CORGI              "corgi hide"
#define MATERIAL_HIDE_CAT                "cat hide"
#define MATERIAL_HIDE_MONKEY             "monkey hide"
#define MATERIAL_HIDE_LIZARD             "lizard hide"
#define MATERIAL_HIDE_ALIEN              "alien hide"
#define MATERIAL_HIDE_HUMAN              "human hide"

// Wood.
#define MATERIAL_WOOD                    "wood"
#define MATERIAL_BIRCH                   "birch wood"
#define MATERIAL_MAHOGANY                "mahogany wood"
#define MATERIAL_MAPLE                   "maple wood"
#define MATERIAL_BAMBOO                  "bamboo wood"
#define MATERIAL_EBONY                   "ebony wood"
#define MATERIAL_WALNUT                  "walnut wood"
#define MATERIAL_YEW                     "yew wood"
#define MATERIAL_WOOD_HOLO               "holowood"
#define MATERIAL_WOOD_LOG                "log"
#define MATERIAL_WOOD_BRANCH             "branch"

// Cloth and related.
#define MATERIAL_CLOTH                   "cloth"
#define MATERIAL_COTTON                  "cotton"
#define MATERIAL_CARPET                  "carpet"
#define MATERIAL_CARPET_BLACK            "carpet_black"
#define MATERIAL_CARPET_BLUE             "carpet_blue"
#define MATERIAL_CARPET_CYAN             "carpet_cyan"
#define MATERIAL_CARPET_GREEN            "carpet_green"
#define MATERIAL_CARPET_ORANGE           "carpet_orange"
#define MATERIAL_CARPET_PURPLE           "carpet_purple"
#define MATERIAL_CARPET_RED              "carpet_red"

#define MATERIAL_ALTERATION_NONE 0
#define MATERIAL_ALTERATION_NAME 1
#define MATERIAL_ALTERATION_DESC 2
#define MATERIAL_ALTERATION_COLOR 4
#define MATERIAL_ALTERATION_ALL (~MATERIAL_ALTERATION_NONE)

#define MATERIAL_ARMOR_COEFFICENT 0.05
