#define MATERIAL_PLASTIC                 "plastic"
#define MATERIAL_PLASTIC_HOLO            "holoplastic"
#define MATERIAL_PLASTEEL                "plasteel"
#define MATERIAL_STEEL                   "steel"
#define MATERIAL_GLASS                   "glass"
#define MATERIAL_GLASS_REINFORCED        "rglass"
#define MATERIAL_GLASS_WIRED             "wired glass"
#define MATERIAL_GLASS_PHORON            "borosilicate glass"
#define MATERIAL_GLASS_REINFORCED_PHORON "reinforced borosilicate glass"
#define MATERIAL_GOLD                    "gold"
#define MATERIAL_SILVER                  "silver"
#define MATERIAL_DIAMOND                 "diamond"
#define MATERIAL_PHORON                  "phoron"
#define MATERIAL_URANIUM                 "uranium"
#define MATERIAL_SANDSTONE               "sandstone"
#define MATERIAL_CONCRETE                "concrete"
#define MATERIAL_IRON                    "iron"
#define MATERIAL_PLATINUM                "platinum"
#define MATERIAL_BRONZE                  "bronze"
#define MATERIAL_OSMIUM                  "osmium"
#define MATERIAL_MARBLE                  "marble"
#define MATERIAL_CULT                    "cult"
#define MATERIAL_CULT_REINFORCED         "cult_reinforced"
#define MATERIAL_TITANIUM                "titanium"
#define MATERIAL_SAND                    "sand"
#define MATERIAL_DIONA                   "biomass"
#define MATERIAL_VAURCA                  "alien biomass"
#define MATERIAL_TRITIUM                 "tritium"
#define MATERIAL_HYDROGEN_METALLIC       "mhydrogen"
#define MATERIAL_ELEVATOR                "elevatorium"
#define MATERIAL_SHUTTLE                 "shuttle"
#define MATERIAL_SHUTTLE_SKRELL          "skrell"
#define MATERIAL_RUST                    "rust"
#define MATERIAL_CARDBOARD               "cardboard"

// Leathers and related.
#define MATERIAL_RESIN                   "resin"
#define MATERIAL_LEATHER                 "leather"
#define MATERIAL_BONE                    "bone"
#define MATERIAL_BONE_CURSED             "cursed bone"
#define MATERIAL_HIDE                    "hide"
#define MATERIAL_HIDE_CORGI              "corgi hide"
#define MATERIAL_HIDE_CAT                "cat hide"
#define MATERIAL_HIDE_MONKEY             "monkey hide"
#define MATERIAL_HIDE_LIZARD             "lizard hide"
#define MATERIAL_HIDE_ALIEN              "alien hide"
#define MATERIAL_HIDE_HUMAN              "human hide"

// Wood.
#define MATERIAL_WOOD                    "wood"
#define MATERIAL_WOOD_HOLO               "holowood"
#define MATERIAL_WOOD_LOG                "log"
#define MATERIAL_WOOD_BRANCH             "branch"

// Cloth and related.
#define MATERIAL_CLOTH                   "cloth"
#define MATERIAL_COTTON                  "cotton"
#define MATERIAL_CARPET                  "carpet"
#define MATERIAL_CLOTH_TEAL              "teal"
#define MATERIAL_CLOTH_BLACK             "black"
#define MATERIAL_CLOTH_GREEN             "green"
#define MATERIAL_CLOTH_PURPLE            "purple"
#define MATERIAL_CLOTH_BLUE              "blue"
#define MATERIAL_CLOTH_BEIGE             "beige"
#define MATERIAL_CLOTH_LIME              "lime"

