#define RENWICKS / 500
#define JOULES * 500

#define MODEFLAG_HYPERKINTEIC 1
#define MODEFLAG_PHOTONIC 2
#define MODEFLAG_HUMANOIDS 3
#define MODEFLAG_AORGANIC 4
#define MODEFLAG_NONHUMANS 5
#define MODEFLAG_ATMOSPHERIC 6
#define MODEFLAG_HULL 7
#define MODEFLAG_MODULATE 8
#define MODEFLAG_OVERCHARGE 9
