#define SECTOR_ROMANOVICH			"Romanovich Cloud"
#define SECTOR_TAU_CETI				"Tau Ceti"
#define SECTOR_CORP_ZONE			"Corporate Reconstruction Zone"
#define SECTOR_BADLANDS				"Badlands"
#define SECTOR_NEW_ANKARA			"New Ankara"
#define SECTOR_SRANDMARR			"S'rand'marr"
#define SECTOR_NRRAHRAHUL			"Nrrahrahul"
#define SECTOR_GAKAL				"Gakal"
#define SECTOR_UUEOAESA				"Uueoa-Esa"