#define SPECIES_HUMAN				"Human"
#define SPECIES_HUMAN_OFFWORLD		"Off-Worlder Human"
#define SPECIES_SKRELL				"Skrell"
#define SPECIES_UNATHI				"Unathi"
#define SPECIES_DIONA				"Diona"

#define SPECIES_TAJARA				"Tajara"
#define SPECIES_TAJARA_ZHAN			"Zhan-Khazan Tajara"
#define SPECIES_TAJARA_MSAI			"M'sai Tajara"

#define SPECIES_VAURCA_WORKER		"Vaurca Worker"
#define SPECIES_VAURCA_WARRIOR		"Vaurca Warrior"
#define SPECIES_VAURCA_BREEDER		"Vaurca Breeder"
#define SPECIES_VAURCA_WARFORM		"Vaurca Warform"

#define SPECIES_IPC					"Baseline Frame"
#define SPECIES_IPC_SHELL			"Shell Frame"
#define SPECIES_IPC_G1				"Hephaestus G1 Industrial Frame"
#define SPECIES_IPC_G2				"Hephaestus G2 Industrial Frame"
#define SPECIES_IPC_XION			"Xion Industrial Frame"
#define SPECIES_IPC_ZENGHU			"Zeng-Hu Mobility Frame"
#define SPECIES_IPC_BISHOP			"Bishop Accessory Frame"

#define SPECIES_IPC_SHELL_ROGUE		"Rogue Shell"
#define SPECIES_IPC_XION_REMOTE		"Remote Xion Industrial Frame"
#define SPECIES_IPC_UNBRANDED		"Unbranded Frame"
#define SPECIES_IPC_UNBRANDED_REMOTE	"Remote Unbranded Frame"
#define SPECIES_IPC_TERMINATOR		"Military Frame"

#define SPECIES_SLIMEPERSON			"Slime"

#define SPECIES_SKELETON			"Skeleton"
#define SPECIES_CULTGHOST			"Apparition"
#define SPECIES_ZOMBIE				"Zombie"
#define SPECIES_ZOMBIE_TAJARA		"Tajara Zombie"
#define SPECIES_ZOMBIE_UNATHI		"Unathi Zombie"
#define SPECIES_ZOMBIE_SKRELL		"Skrell Zombie"
#define SPECIES_SHADOW				"Shadow"

#define SPECIES_MONKEY				"Monkey"
#define SPECIES_MONKEY_SKRELL		"Neaera"
#define SPECIES_MONKEY_UNATHI		"Stok"
#define SPECIES_MONKEY_TAJARA		"Farwa"
#define SPECIES_MONKEY_TAJARA_ZHAN	"Zhan-Khazan Farwa"
#define SPECIES_MONKEY_TAJARA_MSAI	"M'sai Farwa"
#define SPECIES_MONKEY_VAURCA		"V'krexi"

#define SPECIES_GOLEM_COAL			"Coal Golem"
#define SPECIES_GOLEM_IRON			"Iron Golem"
#define SPECIES_GOLEM_BRONZE		"Bronze Golem"
#define SPECIES_GOLEM_STEEL			"Steel Golem"
#define SPECIES_GOLEM_PLASTEEL		"Plasteel Golem"
#define SPECIES_GOLEM_TITANIUM		"Titanium Golem"
#define SPECIES_GOLEM_CLOTH			"Cloth Golem"
#define SPECIES_GOLEM_CARDBOARD		"Cardboard Golem"
#define SPECIES_GOLEM_GLASS			"Glass Golem"
#define SPECIES_GOLEM_PHORON		"Phoron Golem"
#define SPECIES_GOLEM_SILVER		"Silver Golem"
#define SPECIES_GOLEM_GOLD			"Gold Golem"
#define SPECIES_GOLEM_HYDROGEN		"Metallic Hydrogen Golem"
#define SPECIES_GOLEM_WOOD			"Wood Golem"
#define SPECIES_GOLEM_DIAMOND		"Diamond Golem"
#define SPECIES_GOLEM_MARBLE		"Marble Golem"
#define SPECIES_GOLEM_SAND			"Sand Golem"
#define SPECIES_GOLEM_PLASTIC		"Plastic Golem"
#define SPECIES_GOLEM_URANIUM		"Uranium Golem"
#define SPECIES_GOLEM_MEAT			"Homunculus"
#define SPECIES_GOLEM_ADAMANTINE	"Adamantine Golem"


#define BODYTYPE_HUMAN				"Human"
#define BODYTYPE_SKRELL				"Skrell"
#define BODYTYPE_UNATHI				"Unathi"
#define BODYTYPE_DIONA				"Diona"
#define BODYTYPE_TAJARA				"Tajara"

#define BODYTYPE_VAURCA				"Vaurca"
#define BODYTYPE_VAURCA_BREEDER		"Vaurca Breeder"
#define BODYTYPE_VAURCA_WARFORM		"Vaurca Warform"

#define BODYTYPE_IPC				"Machine"
#define BODYTYPE_IPC_INDUSTRIAL		"Heavy Machine"
#define BODYTYPE_IPC_ZENGHU			"Zeng-Hu Mobility Frame"
#define BODYTYPE_IPC_BISHOP			"Bishop Accessory Frame"

#define BODYTYPE_GOLEM				"Golem"
#define BODYTYPE_MONKEY				"Monkey"

#define BODYTYPE_SKELETON			"Skeleton"
#define BODYTYPE_CULTGHOST			"Apparition"