#define SPECIES_HUMAN				"Human"
#define SPECIES_HUMAN_OFFWORLD		"Off-Worlder Human"
#define SPECIES_UNATHI				"Unathi"
#define SPECIES_DIONA				"Diona"

#define SPECIES_SKRELL				"Xiialt Skrell"
#define SPECIES_SKRELL_AXIORI		"Axiori Skrell"

#define SPECIES_TAJARA				"Tajara"
#define SPECIES_TAJARA_ZHAN			"Zhan-Khazan Tajara"
#define SPECIES_TAJARA_MSAI			"M'sai Tajara"

#define SPECIES_VAURCA_WORKER		"Vaurca Worker"
#define SPECIES_VAURCA_WARRIOR		"Vaurca Warrior"
#define SPECIES_VAURCA_BREEDER		"Vaurca Breeder"
#define SPECIES_VAURCA_WARFORM		"Vaurca Warform"
#define SPECIES_VAURCA_BULWARK		"Vaurca Bulwark"

#define SPECIES_IPC					"Baseline Frame"
#define SPECIES_IPC_SHELL			"Shell Frame"
#define SPECIES_IPC_HEAVY			"Heavy frame"

#define SPECIES_IPC_G1				"Hephaestus G1 Industrial Frame"
#define SPECIES_IPC_XION			"Xion Industrial Frame"
#define SPECIES_IPC_SHELL_ROGUE		"Rogue Shell"
#define SPECIES_IPC_XION_REMOTE		"Remote Xion Industrial Frame"
#define SPECIES_IPC_UNBRANDED		"Unbranded Frame"
#define SPECIES_IPC_UNBRANDED_REMOTE	"Remote Unbranded Frame"
#define SPECIES_IPC_TERMINATOR		"Military Frame"

#define SPECIES_SLIMEPERSON			"Slime"

#define SPECIES_SKELETON			"Skeleton"
#define SPECIES_CULTGHOST			"Apparition"
#define SPECIES_ZOMBIE				"Zombie"
#define SPECIES_ZOMBIE_TAJARA		"Tajara Zombie"
#define SPECIES_ZOMBIE_UNATHI		"Unathi Zombie"
#define SPECIES_ZOMBIE_SKRELL		"Skrell Zombie"
#define SPECIES_REVENANT			"Revenant"

#define SPECIES_MONKEY				"Monkey"
#define SPECIES_MONKEY_SKRELL		"Neaera"
#define SPECIES_MONKEY_UNATHI		"Stok"
#define SPECIES_MONKEY_TAJARA		"Farwa"
#define SPECIES_MONKEY_TAJARA_ZHAN	"Zhan-Khazan Farwa"
#define SPECIES_MONKEY_TAJARA_MSAI	"M'sai Farwa"
#define SPECIES_MONKEY_VAURCA		"V'krexi"

#define SPECIES_GOLEM_COAL			"Coal Golem"
#define SPECIES_GOLEM_IRON			"Iron Golem"
#define SPECIES_GOLEM_BRONZE		"Bronze Golem"
#define SPECIES_GOLEM_STEEL			"Steel Golem"
#define SPECIES_GOLEM_PLASTEEL		"Plasteel Golem"
#define SPECIES_GOLEM_TITANIUM		"Titanium Golem"
#define SPECIES_GOLEM_CLOTH			"Cloth Golem"
#define SPECIES_GOLEM_CARDBOARD		"Cardboard Golem"
#define SPECIES_GOLEM_GLASS			"Glass Golem"
#define SPECIES_GOLEM_PHORON		"Phoron Golem"
#define SPECIES_GOLEM_SILVER		"Silver Golem"
#define SPECIES_GOLEM_GOLD			"Gold Golem"
#define SPECIES_GOLEM_HYDROGEN		"Metallic Hydrogen Golem"
#define SPECIES_GOLEM_WOOD			"Wood Golem"
#define SPECIES_GOLEM_DIAMOND		"Diamond Golem"
#define SPECIES_GOLEM_MARBLE		"Marble Golem"
#define SPECIES_GOLEM_SAND			"Sand Golem"
#define SPECIES_GOLEM_PLASTIC		"Plastic Golem"
#define SPECIES_GOLEM_URANIUM		"Uranium Golem"
#define SPECIES_GOLEM_MEAT			"Homunculus"
#define SPECIES_GOLEM_ADAMANTINE	"Adamantine Golem"
#define SPECIES_GOLEM_TECHOMANCER	"Technomancer Golem"


#define BODYTYPE_HUMAN				"Human"
#define BODYTYPE_SKRELL				"Skrell"
#define BODYTYPE_UNATHI				"Unathi"
#define BODYTYPE_DIONA				"Diona"
#define BODYTYPE_TAJARA				"Tajara"

#define BODYTYPE_VAURCA				"Vaurca"
#define BODYTYPE_VAURCA_BREEDER		"Vaurca Breeder"
#define BODYTYPE_VAURCA_BULWARK		"Vaurca Bulwark"
#define BODYTYPE_VAURCA_WARFORM		"Vaurca Warform"

#define BODYTYPE_IPC				"Machine"
#define BODYTYPE_IPC_INDUSTRIAL		"Heavy Machine"

#define BODYTYPE_GOLEM				"Golem"
#define BODYTYPE_MONKEY				"Monkey"

#define BODYTYPE_SKELETON			"Skeleton"
#define BODYTYPE_CULTGHOST			"Apparition"


#define SPECIES_PAIN_MOD				"pain_mod"
#define SPECIES_BRUTE_MOD				"brute_mod"
#define SPECIES_BURN_MOD				"burn_mod"
#define SPECIES_OXY_MOD					"oxy_mod"
#define SPECIES_TOXINS_MOD				"toxins_mod"
#define SPECIES_RADIATION_MOD			"radiation_mod"
#define SPECIES_FLASH_MOD				"flash_mod"
#define SPECIES_FALL_MOD				"fall_mod"
#define SPECIES_GRAB_MOD				"grab_mod"
#define SPECIES_RESIST_MOD				"resist_mod"
#define SPECIES_METABOLISM_MOD			"metabolism_mod"
#define SPECIES_BLEED_MOD				"bleed_mod"
#define SPECIES_HAZARD_HIGH_PRESSURE	"hazard_high_pressure"
#define SPECIES_WARNING_HIGH_PRESSURE	"warning_high_pressure"
#define SPECIES_WARNING_LOW_PRESSURE	"warning_low_pressure"
#define SPECIES_HAZARD_LOW_PRESSURE		"hazard_low_pressure"
#define SPECIES_SLOWDOWN				"slowdown"
#define SPECIES_STAMINA_RECOVERY		"stamina_recovery"
#define SPECIES_SPRINT_SPEED_FACTOR		"sprint_speed_factor"
#define SPECIES_SPRINT_COST_FACTOR		"sprint_cost_factor"
#define SPECIES_EXHAUST_THRESHOLD		"exhaust_threshold"
