//Remember, +1 accuracy means that accuracy is calculated 1 tile closer. -1 is the opposite.

//accuracy = PISTOL_ACCURACY_UNWIELDED
//accuracy_wielded = PISTOL_ACCURACY_WIELDED


#define PISTOL_ACCURACY_WIELDED 1
#define PISTOL_ACCURACY_UNWIELDED -2

#define SMG_ACCURACY_WIELDED 2
#define SMG_ACCURACY_UNWIELDED -2

#define RIFLE_ACCURACY_WIELDED 3
#define RIFLE_ACCURACY_UNWIELDED -3

#define HEAVY_ACCURACY_WIELDED 2
#define HEAVY_ACCURACY_UNWIELDED -4

#define SNIPER_ACCURACY_WIELDED -3
#define SNIPER_ACCURACY_UNWIELDED -5

#define SHOTGUN_ACCURACY_WIELDED 1
#define SHOTGUN_ACCURACY_UNWIELDED -5

#define STAFF_ACCURACY_WIELDED 3
#define STAFF_ACCURACY_UNWIELDED -2