// https://www.aqua-calc.com/calculate/volume-to-weight/substance/
// https://www.engineeringtoolbox.com/specific-heat-fluids-d_151.html //USE THE TABLE ON THE LEFT
// https://www.engineeringtoolbox.com/specific-heat-solids-d_154.html //USE THE TABLE ON THE RIGHT
// http://www2.ucdsb.on.ca/tiss/stretton/database/specific_heat_capacity_table.html
// https://www.nuclear-power.net/radium-specific-heat-latent-heat-vaporization-fusion/


#define CALC_SPECIFIC_HEAT_2(NUM1,NUM2) return (NUM1*NUM2)/2
#define CALC_SPECIFIC_HEAT_3(NUM1,NUM2,NUM3) return (NUM1*NUM2*NUM3)/3
#define CALC_SPECIFIC_HEAT_4(NUM1,NUM2,NUM3,NUM4) return (NUM1*NUM2*NUM3*NUM4)/4


#define UNITS_TO_METRIC_TEASPOON 1			//How many teaspoons are in a unit?

#define GRAMS_PER_UNIT_DEFAULT				GRAMS_PER_UNIT_WATER
#define GRAMS_PER_UNIT_ALUMINUM 			UNITS_TO_METRIC_TEASPOON * 13.5
#define GRAMS_PER_UNIT_AMMONIA 				UNITS_TO_METRIC_TEASPOON * 3.41
#define GRAMS_PER_UNIT_ACETONE 				UNITS_TO_METRIC_TEASPOON * 3.96
#define GRAMS_PER_UNIT_CARBON 				UNITS_TO_METRIC_TEASPOON * 0.4
#define GRAMS_PER_UNIT_ALCOHOL 				UNITS_TO_METRIC_TEASPOON * 3.93	//Alcohol, methyl.
#define GRAMS_PER_UNIT_ETHANOL 				UNITS_TO_METRIC_TEASPOON * 3.95
#define GRAMS_PER_UNIT_BUTANOL 				UNITS_TO_METRIC_TEASPOON * 2.87 //n-Butane
#define GRAMS_PER_UNIT_COPPER 				UNITS_TO_METRIC_TEASPOON * 44.75
#define GRAMS_PER_UNIT_GOLD 				UNITS_TO_METRIC_TEASPOON * 96.6
#define GRAMS_PER_UNIT_HYDRAZINE 			GRAMS_PER_UNIT_DEFAULT //NO CLUE, HONESTLY.
#define GRAMS_PER_UNIT_IRON 				UNITS_TO_METRIC_TEASPOON * 39.37
#define GRAMS_PER_UNIT_LITHIUM 				UNITS_TO_METRIC_TEASPOON * 2.67
#define GRAMS_PER_UNIT_MERCURY 				UNITS_TO_METRIC_TEASPOON * 67.67
#define GRAMS_PER_UNIT_PHOSPHORUS 			UNITS_TO_METRIC_TEASPOON * 11.7
#define GRAMS_PER_UNIT_POTASSIUM 			UNITS_TO_METRIC_TEASPOON * 4.28
#define GRAMS_PER_UNIT_RADIUM 				UNITS_TO_METRIC_TEASPOON * 27.5
#define GRAMS_PER_UNIT_POLYTRINIC_ACID 		GRAMS_PER_UNIT_HYDROCHLORIC_ACID //NO CLUE, HONESTLY.
#define GRAMS_PER_UNIT_SULPHURIC_ACID 		UNITS_TO_METRIC_TEASPOON * 9.13
#define GRAMS_PER_UNIT_HYDROCHLORIC_ACID 	UNITS_TO_METRIC_TEASPOON * 8.2
#define GRAMS_PER_UNIT_ICE 					UNITS_TO_METRIC_TEASPOON * 2.97
#define GRAMS_PER_UNIT_SILICON 				UNITS_TO_METRIC_TEASPOON * 12.66
#define GRAMS_PER_UNIT_SODIUM 				UNITS_TO_METRIC_TEASPOON * 5.26
#define GRAMS_PER_UNIT_SODIUM_CHLORIDE 		UNITS_TO_METRIC_TEASPOON * 10.85
#define GRAMS_PER_UNIT_SUGAR 				UNITS_TO_METRIC_TEASPOON * 4.01
#define GRAMS_PER_UNIT_SULFUR 				UNITS_TO_METRIC_TEASPOON * 10.35
#define GRAMS_PER_UNIT_TUNGSTEN 			UNITS_TO_METRIC_TEASPOON * 96.25
#define GRAMS_PER_UNIT_WATER 				UNITS_TO_METRIC_TEASPOON * 5.53

#define SPECIFIC_HEAT_DEFAULT 				SPECIFIC_HEAT_WATER
#define SPECIFIC_HEAT_ALUMINUM 				GRAMS_PER_UNIT_ALUMINUM * 0.902
#define SPECIFIC_HEAT_AMMONIA 			 	GRAMS_PER_UNIT_AMMONIA * 4.61
#define SPECIFIC_HEAT_ACETONE 			 	GRAMS_PER_UNIT_ACETONE * 2.15
#define SPECIFIC_HEAT_CARBON 			 	GRAMS_PER_UNIT_CARBON * 0.71
#define SPECIFIC_HEAT_ALCOHOL			 	GRAMS_PER_UNIT_ALCOHOL * 2.47 //Alcohol, methyl.
#define SPECIFIC_HEAT_ETHANOL			 	GRAMS_PER_UNIT_ETHANOL * 2.3
#define SPECIFIC_HEAT_BUTANOL			 	GRAMS_PER_UNIT_ETHANOL * 2.87 //n-Butane
#define SPECIFIC_HEAT_COPPER				GRAMS_PER_UNIT_COPPER *  0.385
#define SPECIFIC_HEAT_GOLD					GRAMS_PER_UNIT_GOLD * 0.129
#define SPECIFIC_HEAT_HYDRAZINE				SPECIFIC_HEAT_DEFAULT // NO CLUE, HONESTLY.
#define SPECIFIC_HEAT_IRON					GRAMS_PER_UNIT_IRON * 0.450
#define SPECIFIC_HEAT_LITHIUM				GRAMS_PER_UNIT_LITHIUM * 3.56
#define SPECIFIC_HEAT_MERCURY 				GRAMS_PER_UNIT_MERCURY * 0.140
#define SPECIFIC_HEAT_PHOSPHORUS 			GRAMS_PER_UNIT_PHOSPHORUS * 0.73 //I CHEATED AND JUST LOOKED UP SULPHER, #YOLO
#define SPECIFIC_HEAT_POTASSIUM 			GRAMS_PER_UNIT_POTASSIUM * 0.75
#define SPECIFIC_HEAT_RADIUM				GRAMS_PER_UNIT_RADIUM * 0.12
#define SPECIFIC_HEAT_POLYTRINIC_ACID 		SPECIFIC_HEAT_HYDROCHLORIC_ACID //NO CLUE, HONESTLY.
#define SPECIFIC_HEAT_SULPHURIC_ACID 		GRAMS_PER_UNIT_SULPHURIC_ACID * 1.34
#define SPECIFIC_HEAT_HYDROCHLORIC_ACID 	GRAMS_PER_UNIT_HYDROCHLORIC_ACID * 3.14
#define SPECIFIC_HEAT_ICE 					GRAMS_PER_UNIT_ICE * 2.03
#define SPECIFIC_HEAT_SILICON 				GRAMS_PER_UNIT_SILICON * 3.14
#define SPECIFIC_HEAT_SODIUM 				GRAMS_PER_UNIT_SODIUM * 1.38
#define SPECIFIC_HEAT_SODIUM_CHLORIDE		GRAMS_PER_UNIT_SODIUM_CHLORIDE * 0.864
#define SPECIFIC_HEAT_SUGAR					GRAMS_PER_UNIT_SUGAR * 1.244
#define SPECIFIC_HEAT_SULFUR				GRAMS_PER_UNIT_SULFUR * 0.73
#define SPECIFIC_HEAT_TUNGSTEN				GRAMS_PER_UNIT_TUNGSTEN * 0.134
#define SPECIFIC_HEAT_WATER 				GRAMS_PER_UNIT_WATER * 4.18

//COMPOUNDS
#define SPECIFIC_HEAT_INAPROVALINE 			CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_ACETONE,SPECIFIC_HEAT_CARBON,SPECIFIC_HEAT_SUGAR)
#define SPECIFIC_HEAT_BICARIDINE 			CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_INAPROVALINE,SPECIFIC_HEAT_CARBON)
#define SPECIFIC_HEAT_KELOTANE 				CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_CARBON,SPECIFIC_HEAT_SILICON)
#define SPECIFIC_HEAT_DERMALINE 			CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_KELOTANE,SPECIFIC_HEAT_ACETONE,SPECIFIC_HEAT_PHOSPHORUS)
#define SPECIFIC_HEAT_DYLOVENE 				CALC_SPECIFIC_HEAT_3(SPECIFC_HEAT_SILICON,SPECIFIC_HEAT_POTASSIUM,SPECIFIC_HEAT_AMMONIA)
#define SPECIFIC_HEAT_DEXALIN 				CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_ACETONE*2,SPECIFIC_HEAT_PHORON*0.1)
#define SPECIFIC_HEAT_DEXALIN_PLUS			CALC_SPECIFIC_HEAT_3(SPECIFC_HEAT_DEXALIN,SPECIFIC_HEAT_IRON,SPECIFIC_HEAT_CARBON)
#define SPECIFIC_HEAT_TRICORDRAZINE			CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_INAPROVALINE,SPECIFIC_HEAT_DYLOVENE)
#define SPECIFIC_HEAT_CRYOXADONE			CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_DEXALIN,SPECIFIC_HEAT_WATER,SPECIFIC_HEAT_ACETONE)*1.25 //UNIQUE, ACTUALLY GETS A BIT COLD WHEN MIXED.
#define SPECIFIC_HEAT_CLONEXADONE			CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_CRYOXADONE,SPECIFIC_HEAT_SODIUM,SPECIFIC_HEAT_PHORON*0.1) * (3/2)
#define SPECIFIC_HEAT_PARACETAMOL			CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_TRAMADOL,SPECIFIC_HEAT_WATER,SPECIFIC_HEAT_SUGAR)
#define SPECIFIC_HEAT_TRAMADOL				CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_INAPROVALINE,SPECIFIC_HEAT_ETHANOL,GRAMS_PER_UNIT_ACETONE)
#define SPECIFIC_HEAT_OXYCODONE				CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_TRAMADOL,SPECIFIC_HEAT_ETHANOL) * (2/1)
#define SPECIFIC_HEAT_SYNAPZINE				CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_SUGAR,SPECIFIC_HEAT_LITHIUM,SPECIFIC_HEAT_WATER)
#define SPECIFIC_HEAT_ALKYSINE				CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_HYDROCHLORIC_ACID,SPECIFIC_HEAT_AMMONIA,SPECIFIC_HEAT_DYLOVENE) * (3/2)
#define SPECIFIC_HEAT_IMIDAZOLINE			CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_CARBON,SPECIFIC_HEAD_HYDRAZINE,SPECIFIC_HEAT_DYLOVENE) * (3/2)
#define SPECIFIC_HEAT_PERIDAXON				CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_BICARDINE,SPECIFIC_HEAT_CLONEXADONE)
#define SPECIFIC_HEAT_RYETALYN				CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_ARITHRAZINE,SPECIFIC_HEAT_CARBON)
#define SPECIFIC_HEAT_HYPERZINE				CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_SUGAR,SPECIFIC_HEAT_PHOSPHORUS,SPECIFIC_HEAT_SULFUR)
#define SPECIFIC_HEAT_ETHYLREDOXRAZINE		CALC_SPECIFIC_HEAT_3(SPECIFIC_HEAT_ACETONE,SPECIFIC_HEAT_DYLOVENE,SPECIFIC_HEAT_CARBON)
#define SPECIFIC_HEAT_HYRONALIN				CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_RADIUM,SPECIFIC_HEAT_DYLOVENE)
#define SPECIFIC_HEAT_ARITHRAZINE			CALC_SPECIFIC_HEAT_2(SPECIFIC_HEAT_HYRONALIN,SPECIFIC_HEAT_HYDRAZINE)