/decl/nanomachine_effect/metabolic_hijack
	name = "Metabolic Hijack"
	desc = "Allows nanomachines to use ATP generated by the body to fuel themselves. To compensate, the body burns more nutrients and water."

	program_capacity_usage = 0

	var/rate_increase = 0.3

/decl/nanomachine_effect/nanomachines_son/do_nanomachine_effect(var/datum/nanomachine/parent, var/mob/living/carbon/human/H)
	H.adjustNutritionLoss(H.nutrition_loss * (H.nutrition_attrition_rate / 2))
	H.adjustHydrationLoss(H.hydration_loss * (H.hydration_attrition_rate / 2))

/decl/nanomachine_effect/metabolic_hijack/add_effect(var/datum/nanomachine/parent)
	parent.regen_rate += rate_increase

/decl/nanomachine_effect/metabolic_hijack/remove_effect(var/datum/nanomachine/parent)
	parent.regen_rate -= rate_increase