// This is a parody of Cards Against Humanity (https://en.wikipedia.org/wiki/Cards_Against_Humanity)
// which is licensed under CC BY-NC-SA 2.0, the full text of which can be found at the following URL:
// https://creativecommons.org/licenses/by-nc-sa/2.0/legalcode

//Ported from Polaris;
//To be rewritten to be made more 'in-universe' and less 'meta-SS13 references', as amusing the latter can be.
//Pretty sure people in-universe wouldn't exactly see things the same way we SS13 players do

/obj/item/deck/cah
	name = "\improper CAG deck (white)"
	desc = "The ever-popular Cards Against The Galaxy word game. This is the white deck."
	icon_state = "cag_white"
	var/blanks = 5

/obj/item/deck/cah/black
	name = "\improper CAG deck (black)"
	desc = "The ever-popular Cards Against The Galaxy word game. This is the black deck."
	icon_state = "cag_black"
	blanks = 0

/obj/item/deck/cah/Initialize()
	. = ..()
	var/datum/playingcard/P
	for(var/cardtext in card_text_list)
		P = new()
		P.name = "[cardtext]"
		P.card_icon = "[icon_state]_card"
		P.back_icon = "[icon_state]_card_back"
		cards += P
	if(!blanks)
		return
	for(var/x=1 to blanks)
		P = new()
		P.name = "Blank Card"
		P.card_icon = "[icon_state]_card_back"
		P.back_icon = "[icon_state]_card_back"

// Black cards.
/obj/item/deck/cah/black/card_text_list = list(
	"Why am I itchy?",
	"Today, police shot ____.",
	"Our local chaplain is worshipping _____.",
	"My grandparents ordered a crate full of _____ from the catalogue.",
	"The FIB was called due to ______.",
	"Alert! The Sol Navy has armed themselves with _____.",
	"Order received: ________ is your master.",
	"Order received: ________ is the enemy.",
	"_____ blew a hole in the wall.",
	"Today, researchers found an artefact that made people ____ and ____. (Pick 2)",
	"There was a rap battle between ____ and ____. (Pick 2)",
	"Caution, ______ have been detected in collision course with the planet.",
	"Today's kitchen menu includes _______.",
	"What did space pirates want when they attacked our home?",
	"I think our boss is insane. He just demanded ______ in his office.",
	"Fuckin' scientists, they just turned the entire population of Scottsdan into _______ .",
	"Fuckin' activists, they just converted Mendell City into ______ .",
	"What's my fetish?",
	"Next up on TCFL's Got Talent: ________ .",
	"Next up on Biesel's World Cooking Championships: _______ .",
	"Hello, _______ here with _______ . (Pick 2)",
	"No one else was at _______, they wouldn't understand the ______ . (Pick 2)",
	"Why am I shivering?",
	"What is this world coming to? First, ________, now _______ . (Pick 2)",
	"NanoTrasen's morale division decided to use _______ to raise employee morale.",
	"The average junkie's drug of choice is ______ .",
	"I saw an Eridanian dreg make out with ______ the other day.",
	"It is common practice for _______ to ______ on Moghes. (Pick 2)",
	"The colonies of the Coalition of Colonies are really just _____.",
	"The Skrell are celebrating _____ today.",
	"_____ is/are why I'm afraid of hospitals.",
	"_____ used ____ to create their newest invention, _____!  (Draw 2; Pick 3)",
	"Scientists are not allowed to make Gatling _____.",
	"It's not a party until the ____ arrive.",
	"No matter how many Tajara you have, _____ is never acceptable.",
	"No, your robot's first law is NOT to serve _____.",
	"The robots are not disposal bins for your _____.",
	"You can never have too many _____ on board.",
	"Failing to fit ______ up the _____ . (Pick 2)",
	"_____ has no idea what S&M is and _____ shows them. (Pick 2)",
	"What's this in my hand?",
	"My lover left me for ______.",
	"The _____ apocalypse comes.",
	"Hi! I'm Malyr Krissen, and I got hit by ______.",
	"Ah. ______ . Good times.",
	"Well, well. If it isn't _____ .",
	"Please welcome our newest recruit: _____ !",
	"Didn’t you hear? Kazimir Boytsov just got sick from _____ !",
	"\"Tau Ceti has become a beacon of liberty and hope for ______ .\"",
	"\"This colony of the Alliance has been proliferating _____ as potential weapons of mass destruction.\"",
	"What is the president's next speech going to be about?",
	"It's _____ time!",
	"That was a wild party last night. I only remember _____ .",
	"Create a haiku. (Draw 2; Pick 3)",
	"You can't go on like this. Go talk to the doctor about _____ .",
	"And the award goes to...",
	"Look! Over there! It's _____ !",
	"What you call a passion fruit, I call a _____ .",
	"How do I deal with my grief?",
	"Knock knock! Who's there?",
	"Drats! Foiled by _____ AGAIN!"
	)

// White cards.
/obj/item/deck/cah/var/list/card_text_list = list(
	"Those motherfucking carp",
	"Having sex in a sewer outlet",
	"Space 'Nam",
	"Space cowboys",
	"My gardener getting SUPER high",
	"Your boss thinking they're a badass",
	"Being in a religious cult",
	"Racially-biased directives",
	"An Unathi who WON'T STOP FIGHTING",
	"Tajaran fetishists",
	"Bald dogs",
	"Mummy-dear's sweet whispers",
	"Being sucked out into space",
	"Touchy-feely shells",
	"Construction (again)",
	"Tsunami",
	"The ClockWorks on a Tuesday night",
	"Fucking synths",
	"Man-eating purple pod plants",
	"Filling fire extinguishers with hydrogen",
	"Librarians",
	"Squids",
	"Cats",
	"Lizards",
	"Apes",
	"Trees",
	"Ants",
	"Supermatter undergarments",
	"Bluespace",
	"Vending machine tech singularity",
	"Kitchen utensil anomalies",
	"Locked lockers",
	"Energy spatulas",
	"Flashbang shoes",
	"Space whales",
	"Space sharks",
	"Augmented male enhancers",
	"Gyrating barks",
	"Forehead-mounted laser weaponry",
	"Pelvis-mounted laser weaponry",
	"Cardboard cutouts",
	"An obscene amount of rubber ducks",
	"Brain cakes",
	"A drone's game of life.",
	"Anomaly suits",
	"A hydrofarmer smoking reishi",
	"Military-grade baseball bats",
	"Barricading your classroom",
	"An irritatingly chipper robot",
	"Androids hanging out at a bar drinking beer",
	"Flannel lingerie",
	"A seventeen-year-old medical doctor",
	"The throbbing erection that the police chief gets at the thought of shooting something",
	"Trying to stab someone and hugging them instead",
	"Waking up naked in a dark hallway",
	"Horrible cloning accidents",
	"Licking supermatter crystals due to a dare",
	"Your uncle who WON'T STOP buying guns",
	"Teaching a synthetic the Birds and the Bees",
	"Unnecessary surgery",
	"'Youth enhancements'",
	"My addiction to spiders",
	"DOCTOR MAXMAN!",
	"A group of Skrell getting their squish on",
	"Enough soporific to put the entire apartment block down",
	"Delicious New Hai Phongese cuisine",
	"Glorsh-Omega",
	"Miranda Trasen",
	"Michael 'The Mightinator' Frost",
	"Aeson and Lopez-Zhang's love child",
	"Liqin Hsiao-Li's dungeon",
	"Mason's Trasen harem",
	"Lydumila Zavodskoi having an identity crisis",
	"Thanks, Dorn",
	"His Imperial Majesty Emperor Boleslaw Keeser",
	"Humping in a spacesuit",
	"Planetary genocide",
	"Sol III marijuana, baby",
	"Eli's Extravagant Enchiladas",
	"Racism",
	"Interspecific orgies",
	"Punching everyone in their genitals",
	"Legalised bestiality",
	"Balding at 20",
	"A worthless degree",
	"Overly insistent employees",
	"Faulty mechanics",
	"Swarms of flesh-eating nanites",
	"Scientists",
	"Sexy, Sexy Androids",
	"Giant carnivorous plants",
	"Spraying lube on it",
	"Librarians",
	"Unevolved humanoids",
	"Small Trees",
	"My special rocket ship underwear",
	"Artificial intelligence",
	"500 robotic spiders",
	"500 sex bots",
	"Cable ties",
	"Getting sprayed by the soda fountain",
	"RGB 'gamer-grade' drink coasters",
	"Sentient cutlery",
	"Locked garment protection box",
	"Fancy spatulas",
	"Slappy slap hand gloves",
	"Sea bass",
	"Fax machines",
	"20th-century fountain pens",
	"50% functional viagra",
	"Questionably multipurpose lubricant",
	"Eye lasers",
	"Dick lasers",
	"A bicycle",
	"An actual goddamn time machine",
	"That special OTP generator in your bookmarks",
	"Affectionate spammers",
	"Electron-positron annihilation",
	"Non-Venusian Venusian holofilms",
	"An overheating dick chip",
	"Emo robots",
	"Cyborgs printing paper from their mouth",
	"A semi-automatic ballistic handgun",
	"The Fleshmaster",
	"Titanius Aeson's moustache",
	"Walk Like Idris(TM) shoes",
	"The untagged shell that lives in the apartment next to yours",
	"Your company's hiring department",
	"A robot programmed only to scream",
	"Aemaq's sea monsters",
	"A Croskian pilot with a raging coke addiction",
	"Two Skrell in a trenchcoat",
	"The Empire of Dominia",
	"'My shell girlfriend who totally has real emotions, you guys.'",
	"A Tajara that talks in first person",
	"Petty theft",
	"The human rights record of the People's Republic of Adhomai",
	"An inbred Njarir",
	"A freakishly tall Dominian noble",
	"A Scarab with a bag full of wrenches",
	"A hulking industrial IPC programmed to tapdance",
	"Very angry and very GM bees",
	"The brittle, brittle bones of an offworlder",
	"The refreshing chemical waters of Xanu Prime",
	"Monowheel greaser gangs",
	"Your favourite debt collector",
	"A Venusian drug orgy",
	"A Lunarian with an annoying voice and more money than you'll ever see in your life",
	"The galaxy's tallest Skrell",
	"EPMC beating their dregs for no apparent reason",
	"Underground life on Himeo",
	"An all-expense paid vacation to Silversun!",
	"Taking two IPC's tags out and swapping them as a hilarious practical joke",
	"Unresolved sexual tension",
	"Nice black socks"
	)
