ALTER TABLE `ss13_player_preferences`
	MODIFY COLUMN `tgui_fancy` TINYINT(1) NOT NULL DEFAULT 1,
	MODIFY COLUMN `tgui_lock` TINYINT(1) NOT NULL DEFAULT 0,
	MODIFY COLUMN `tgui_inputs` TINYINT(1) NOT NULL DEFAULT 1,
	MODIFY COLUMN `tgui_buttons_large` TINYINT(1) NOT NULL DEFAULT 0,
	MODIFY COLUMN `tgui_inputs_swapped` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `ss13_law` MODIFY COLUMN `felony` TINYINT(1) NOT NULL DEFAULT 0;