#define GEAR_NO_SELECTION 0
#define GEAR_HAS_COLOR_SELECTION 1
#define GEAR_HAS_ADDITIONAL_COLOR_SELECTION 2
#define GEAR_HAS_NAME_SELECTION 4
#define GEAR_HAS_DESC_SELECTION 8
#define GEAR_HAS_COLOR_ROTATION_SELECTION 16