//FMJ
#define FMJ_DAMAGE_MULTIPLIER 1.0
#define FMJ_AP_MULTIPLIER 1.0

//JHP
#define JHP_DAMAGE_MULTIPLIER 1.2
#define JHP_AP_MULTIPLIER 0.75

//AP
#define AP_DAMAGE_MULTIPLIER 0.8
#define AP_AP_MULTIPLIER 1.2

//Polymer
#define POLYMER_DAMAGE_MULTIPLIER 0.8
#define POLYMER_AP_MULTIPLIER 1.1

//Rubber
#define RUBBER_DAMAGE_MULTIPLIER 0.1
#define RUBBER_AP_MULTIPLIER 0.3
#define RUBBER_AGONY_DAMAGE_MULTIPLIER 2.5
