#undef FMJ_DAMAGE_MULTIPLIER
#undef FMJ_AP_MULTIPLIER
#undef JHP_DAMAGE_MULTIPLIER
#undef JHP_AP_MULTIPLIER
#undef AP_DAMAGE_MULTIPLIER
#undef AP_AP_MULTIPLIER
#undef POLYMER_DAMAGE_MULTIPLIER
#undef POLYMER_AP_MULTIPLIER
