/obj/structure/closet/crate/secure/gear_loadout
	desc = "A secure gear crate."
	name = "gear crate"

/obj/structure/closet/crate/secure/gear_loadout/legion
	desc = "A secure crate with Tau Ceti Foreign Legion branding."
	name = "tcfl gear crate"
	icon_state = "tcfl_crate"

/obj/structure/closet/crate/gear_loadout/hephaestus
	desc = "A sturdy crate with Hephaestus Industries branding."
	name = "hephaestus drop crate"
	icon_state = "heph_crate"
	door_hinge = 0.5

/obj/structure/closet/crate/gear_loadout/zenghu
	desc = "A sturdy crate with Zeng-Hu Pharmaceuticals branding."
	name = "zeng-hu drop crate"
	icon_state = "zenghu_crate"
	door_hinge = 0.5

/obj/structure/closet/crate/gear_loadout/einstein
	desc = "A sturdy crate with Einstein Engines branding."
	name = "einstein drop crate"
	icon_state = "einstein_crate"
	door_hinge = 0.5

/obj/structure/closet/crate/gear_loadout/zavodskoi
	desc = "A sturdy crate with Zavodskoi Interstellar branding."
	name = "zavodskoi interstellar drop crate"
	icon_state = "necro_crate"
	door_hinge = 0.5

/obj/structure/closet/crate/secure/gear_loadout/coalition/fill()
	new /obj/item/rig/gunslinger/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/gun/projectile/revolver/mateba(src)
	new /obj/item/ammo_magazine/a454(src)
	new /obj/item/ammo_magazine/a454(src)
	new /obj/item/gun/energy/retro(src)
	new /obj/item/gun/energy/retro(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)

/obj/structure/closet/crate/secure/gear_loadout/coalition_single/fill()
	new /obj/item/clothing/head/helmet/space/void/coalition(src)
	new /obj/item/clothing/suit/space/void/coalition(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)

/obj/structure/closet/crate/secure/gear_loadout/eridani/fill()
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/under/rank/medical/first_responder/pmc/epmc(src)
	new /obj/item/clothing/under/rank/security/pmc/epmc/alt(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/softcap/pmc/epmc(src)
	new /obj/item/clothing/head/softcap/pmc/epmc(src)
	new /obj/item/clothing/head/softcap/pmc/epmc(src)
	new /obj/item/rig/strike/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/gun/energy/gun/nuclear(src)
	new /obj/item/gun/energy/gun/nuclear(src)
	new /obj/item/gun/energy/disruptorpistol/magnum(src)
	new /obj/item/gun/energy/disruptorpistol/magnum(src)
	new /obj/item/gun/energy/net(src)
	new /obj/item/gun/projectile/automatic/x9(src)
	new /obj/item/gun/projectile/automatic/x9(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)

/obj/structure/closet/crate/secure/gear_loadout/eridani_single/fill()
	new /obj/item/clothing/under/rank/security/pmc/epmc(src)
	new /obj/item/clothing/head/beret/corporate/pmc/epmc(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/gun/energy/gun/nuclear(src)
	new /obj/item/gun/energy/disruptorpistol/magnum(src)

/obj/structure/closet/crate/secure/gear_loadout/elyra/fill()
	new /obj/item/rig/elyran/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/gun/projectile/plasma(src)
	new /obj/item/gun/projectile/plasma(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/grenade/chem_grenade/large/phoroncleaner(src)
	new /obj/item/grenade/chem_grenade/large/phoroncleaner(src)

/obj/structure/closet/crate/secure/gear_loadout/elyra_single/fill()
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/gun/projectile/plasma/bolter(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/grenade/chem_grenade/large/phoroncleaner(src)

/obj/structure/closet/crate/secure/gear_loadout/sol/fill()
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/rig/military(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/gun/projectile/shotgun/pump/combat/sol(src)
	new /obj/item/ammo_magazine/assault_shotgun/shells(src)
	new /obj/item/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/storage/box/srf(src)
	new /obj/item/storage/box/league(src)
	new /obj/item/storage/box/fsf(src)
	new /obj/item/storage/box/ssmd(src)
	new /obj/item/storage/box/spg(src)
	new /obj/item/storage/box/mrsp(src)
	new /obj/item/storage/box/sfa(src)

/obj/structure/closet/crate/secure/gear_loadout/sol_single/fill()
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/storage/box/srf(src)
	new /obj/item/storage/box/league(src)
	new /obj/item/storage/box/fsf(src)
	new /obj/item/storage/box/ssmd(src)
	new /obj/item/storage/box/spg(src)
	new /obj/item/storage/box/mrsp(src)
	new /obj/item/storage/box/sfa(src)

/obj/structure/closet/crate/secure/gear_loadout/syndicate_softsuits
	req_access = list()

/obj/structure/closet/crate/secure/gear_loadout/syndicate_softsuits/fill()
	for(var/i in 1 to 6)
		new /obj/item/clothing/head/helmet/space/syndicate/black/orange(src)
		new /obj/item/clothing/suit/space/syndicate/black/orange(src)
		new /obj/item/tank/emergency_oxygen/double(src)

/obj/structure/closet/crate/secure/gear_loadout/frontier_cowboys
	req_access = list()

/obj/structure/closet/crate/secure/gear_loadout/frontier_cowboys/fill()
	for(var/i in 1 to 6)
		var/obj/item/clothing/under/shorts/khaki/pants = new(src)
		var/obj/item/clothing/accessory/dressshirt/rolled/shirt = new(src)
		var/obj/item/clothing/accessory/chaps/chaps = new(src)
		var/obj/item/clothing/accessory/suspenders/suspenders = new(src)
		var/obj/item/clothing/accessory/wcoat_rec/waistcoat = new(src)
		var/obj/item/clothing/head/cowboy/hat = new(src)

		pants.attach_accessory(null, shirt)
		pants.attach_accessory(null, chaps)
		waistcoat.color = COLOR_BEASTY_BROWN
		pants.attach_accessory(null, waistcoat)
		suspenders.color = COLOR_MAROON
		pants.attach_accessory(null, suspenders)
		hat.color = COLOR_BEASTY_BROWN

		new /obj/item/clothing/shoes/cowboy(src)
		new /obj/item/clothing/gloves/fingerless(src)
		new /obj/item/clothing/accessory/holster/thigh(src)
		new /obj/item/melee/whip(src)
		new /obj/item/gun/projectile/revolver/detective(src)
		new /obj/item/gun/projectile/shotgun/pump/lever_action(src)

/obj/structure/closet/crate/secure/gear_loadout/frontier_cowboys/single/fill()
	var/obj/item/clothing/under/shorts/khaki/pants = new(src)
	var/obj/item/clothing/accessory/dressshirt/rolled/shirt = new(src)
	var/obj/item/clothing/accessory/chaps/chaps = new(src)
	var/obj/item/clothing/accessory/suspenders/suspenders = new(src)
	var/obj/item/clothing/accessory/wcoat_rec/waistcoat = new(src)
	var/obj/item/clothing/head/cowboy/hat = new(src)

	pants.attach_accessory(null, shirt)
	pants.attach_accessory(null, chaps)
	waistcoat.color = "#78280b"
	pants.attach_accessory(null, waistcoat)
	suspenders.color = "#521600"
	pants.attach_accessory(null, suspenders)
	hat.color = "#521600"

	new /obj/item/clothing/shoes/cowboy(src)
	new /obj/item/clothing/gloves/fingerless(src)
	new /obj/item/clothing/accessory/holster/thigh(src)
	new /obj/item/melee/whip(src)
	new /obj/item/gun/projectile/revolver/detective(src)
	new /obj/item/gun/projectile/shotgun/pump/lever_action(src)

//Megacorporate suits are used in devices and tools in the uplink
/obj/structure/closet/crate/gear_loadout/zavodskoi/fill()
	new /obj/item/clothing/head/helmet/space/void/zavodskoi(src)
	new /obj/item/clothing/suit/space/void/zavodskoi(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)

/obj/structure/closet/crate/gear_loadout/zenghu/fill()
	new /obj/item/clothing/head/helmet/space/void/zenghu(src)
	new /obj/item/clothing/suit/space/void/zenghu(src)
	new /obj/item/voidsuit_modkit/zeng_skrell(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)

/obj/structure/closet/crate/gear_loadout/hephaestus/fill()
	new /obj/item/clothing/head/helmet/space/void/hephaestus(src)
	new /obj/item/clothing/suit/space/void/hephaestus(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)
	new /obj/item/voidsuit_modkit/heph_unathi(src)

/obj/structure/closet/crate/gear_loadout/einstein/fill()
	new /obj/item/clothing/head/helmet/space/void/einstein(src)
	new /obj/item/clothing/suit/space/void/einstein(src)
	new /obj/item/tank/oxygen/red(src)
	new /obj/item/clothing/shoes/magboots(src)

/obj/structure/closet/crate/secure/gear_loadout/dominia/fill()
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet/armsman(src)
	new /obj/item/clothing/under/dominia/fleet/armsman(src)
	new /obj/item/clothing/under/dominia/fleet/officer(src)
	new /obj/item/clothing/head/dominia/fleet(src)
	new /obj/item/clothing/head/dominia/fleet(src)
	new /obj/item/clothing/head/dominia/fleet(src)
	new /obj/item/clothing/head/dominia/fleet/armsman(src)
	new /obj/item/clothing/head/dominia/fleet/armsman(src)
	new /obj/item/clothing/head/dominia/fleet/officer(src)
	new /obj/item/clothing/suit/storage/dominia/fleet(src)
	new /obj/item/rig/jinxiang/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/gun/projectile/automatic/rifle/dom(src)
	new /obj/item/gun/projectile/automatic/rifle/dom(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/gun/projectile/automatic/tommygun/dom(src)
	new /obj/item/gun/projectile/automatic/tommygun/dom(src)
	new /obj/item/gun/projectile/automatic/tommygun/dom(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/ammo_magazine/submachinemag(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/storage/box/dominianvoid(src)

/obj/structure/closet/crate/secure/gear_loadout/dominia/single/fill()
	new /obj/item/clothing/under/dominia/fleet(src)
	new /obj/item/clothing/under/dominia/fleet/armsman(src)
	new /obj/item/clothing/head/helmet/space/void/dominia(src)
	new /obj/item/clothing/suit/space/void/dominia(src)
	new /obj/item/gun/projectile/automatic/rifle/dom(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/voidsuit_modkit/dominianvoid(src)

/obj/structure/closet/crate/secure/gear_loadout/kosmostrelki/fill()
	new /obj/item/clothing/under/tajaran/cosmonaut(src)
	new /obj/item/clothing/under/tajaran/cosmonaut(src)
	new /obj/item/clothing/under/tajaran/cosmonaut(src)
	new /obj/item/clothing/under/tajaran/cosmonaut(src)
	new /obj/item/clothing/under/tajaran/cosmonaut/commissar(src)
	new /obj/item/clothing/head/tajaran/cosmonaut_commissar(src)
	new /obj/item/rig/tesla/ninja(src)
	new /obj/item/clothing/head/helmet/space/void/pra(src)
	new /obj/item/clothing/head/helmet/space/void/pra(src)
	new /obj/item/clothing/head/helmet/space/void/pra(src)
	new /obj/item/clothing/head/helmet/space/void/pra(src)
	new /obj/item/clothing/head/helmet/space/void/pra(src)
	new /obj/item/clothing/suit/space/void/pra(src)
	new /obj/item/clothing/suit/space/void/pra(src)
	new /obj/item/clothing/suit/space/void/pra(src)
	new /obj/item/clothing/suit/space/void/pra(src)
	new /obj/item/clothing/suit/space/void/pra(src)
	new /obj/item/gun/projectile/automatic/rifle/adhomian(src)
	new /obj/item/gun/projectile/automatic/rifle/adhomian(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/gun/energy/rifle/icelance(src)
	new /obj/item/gun/projectile/pistol/adhomai(src)
	new /obj/item/gun/projectile/pistol/adhomai(src)
	new /obj/item/gun/projectile/pistol/adhomai(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/gun/projectile/deagle/adhomai(src)
	new /obj/item/ammo_magazine/a50(src)
	new /obj/item/ammo_magazine/a50(src)
	new /obj/item/device/augment_implanter/advanced_tesla(src)

/obj/structure/closet/crate/secure/gear_loadout/kosmostrelki/single/fill()
	new /obj/item/clothing/under/tajaran/cosmonaut(src)
	new /obj/item/clothing/head/helmet/space/void/pra(src)
	new /obj/item/clothing/suit/space/void/pra(src)
	new /obj/item/gun/projectile/automatic/rifle/adhomian(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/gun/projectile/pistol/adhomai(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/legion/fill()
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/under/legion/sentinel(src)
	new /obj/item/clothing/under/legion/sentinel(src)
	new /obj/item/clothing/under/legion/legate(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/legion/legate(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/rig/retro(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/shield/riot/tact/legion(src)
	new /obj/item/shield/riot/tact/legion(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/carbine(src)
	new /obj/item/gun/energy/blaster/carbine(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/gun/projectile/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/melee/energy/sword/knife(src)
	new /obj/item/material/twohanded/pike/flag(src)

/obj/structure/closet/crate/secure/gear_loadout/legion/single/fill()
	new /obj/item/clothing/under/legion(src)
	new /obj/item/clothing/head/beret/legion/field(src)
	new /obj/item/clothing/head/helmet/legion(src)
	new /obj/item/clothing/accessory/legion(src)
	new /obj/item/clothing/accessory/legion/specialist(src)
	new /obj/item/rig/retro(src)
	new /obj/item/clothing/suit/storage/vest/legion(src)
	new /obj/item/storage/backpack/legion(src)
	new /obj/item/shield/energy/legion(src)
	new /obj/item/gun/energy/blaster/revolver(src)
	new /obj/item/gun/energy/blaster/carbine(src)
	new /obj/item/melee/energy/sword/knife(src)

/obj/structure/closet/crate/secure/gear_loadout/einstein/fill()
    new /obj/item/rig/merc/einstein(src)
    new /obj/item/clothing/head/helmet/space/void/einstein(src)
    new /obj/item/clothing/head/helmet/space/void/einstein(src)
    new /obj/item/clothing/head/helmet/space/void/einstein(src)
    new /obj/item/clothing/head/helmet/space/void/einstein(src)
    new /obj/item/clothing/head/helmet/space/void/einstein(src)
    new /obj/item/clothing/suit/space/void/einstein(src)
    new /obj/item/clothing/suit/space/void/einstein(src)
    new /obj/item/clothing/suit/space/void/einstein(src)
    new /obj/item/clothing/suit/space/void/einstein(src)
    new /obj/item/clothing/suit/space/void/einstein(src)
    new /obj/item/gun/energy/laser/shotgun(src)
    new /obj/item/gun/energy/rifle(src)
    new /obj/item/gun/energy/rifle(src)
    new /obj/item/gun/projectile/pistol(src)
    new /obj/item/gun/projectile/pistol(src)
    new /obj/item/gun/projectile/pistol(src)
    new /obj/item/gun/projectile/pistol(src)
    new /obj/item/silencer(src)
    new /obj/item/silencer(src)
    new /obj/item/silencer(src)
    new /obj/item/silencer(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/einstein/single/fill()
    new /obj/item/clothing/head/helmet/space/void/einstein(src)
    new /obj/item/clothing/suit/space/void/einstein(src)
    new /obj/item/gun/energy/rifle(src)
    new /obj/item/gun/projectile/pistol(src)
    new /obj/item/silencer(src)
    new /obj/item/ammo_magazine/mc9mm(src)
    new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/hegemony/fill()
	new/obj/item/clothing/under/unathi(src)
	new/obj/item/clothing/under/unathi(src)
	new/obj/item/clothing/under/unathi(src)
	new/obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/head/helmet/space/void/hegemony(src)
	new /obj/item/clothing/head/helmet/space/void/hegemony(src)
	new /obj/item/clothing/head/helmet/space/void/hegemony(src)
	new /obj/item/clothing/head/helmet/space/void/hegemony/captain(src)
	new /obj/item/clothing/suit/space/void/hegemony(src)
	new /obj/item/clothing/suit/space/void/hegemony(src)
	new /obj/item/clothing/suit/space/void/hegemony(src)
	new /obj/item/clothing/suit/space/void/hegemony/captain(src)
	new /obj/item/clothing/suit/armor/unathi/klax(src)
	new /obj/item/clothing/head/helmet/unathi/klax(src)
	new /obj/item/gun/energy/rifle/hegemony(src)
	new /obj/item/gun/energy/rifle/hegemony(src)
	new /obj/item/gun/energy/rifle/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/shield/energy/hegemony(src)
	new /obj/item/shield/energy/hegemony(src)
	new /obj/item/shield/energy/hegemony(src)
	new /obj/item/shield/energy/hegemony(src)
	new /obj/item/gun/projectile/heavysniper/unathi(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/ammo_casing/slugger(src)
	new /obj/item/material/twohanded/pike/flag/hegemony(src)

/obj/structure/closet/crate/secure/gear_loadout/hegemony/single/fill()
	new/obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/head/helmet/space/void/hegemony(src)
	new /obj/item/clothing/suit/space/void/hegemony(src)
	new /obj/item/gun/energy/rifle/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/shield/energy/hegemony(src)

/obj/structure/closet/crate/secure/gear_loadout/kataphract/fill()
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/head/helmet/space/void/kataphract(src)
	new /obj/item/clothing/head/helmet/space/void/kataphract(src)
	new /obj/item/clothing/head/helmet/space/void/kataphract(src)
	new /obj/item/clothing/head/helmet/space/void/kataphract(src)
	new /obj/item/clothing/suit/space/void/kataphract(src)
	new /obj/item/clothing/suit/space/void/kataphract(src)
	new /obj/item/clothing/suit/space/void/kataphract(src)
	new /obj/item/clothing/suit/space/void/kataphract(src)
	new /obj/item/rig/unathi/fancy(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/shield/energy/hegemony/kataphract(src)
	new /obj/item/shield/energy/hegemony/kataphract(src)
	new /obj/item/shield/energy/hegemony/kataphract(src)
	new /obj/item/shield/energy/hegemony/kataphract(src)
	new /obj/item/melee/energy/glaive/hegemony(src)
	new /obj/item/melee/energy/glaive/hegemony(src)
	new /obj/item/melee/hammer/powered/hegemony(src)
	new /obj/item/melee/hammer/powered/hegemony(src)
	new /obj/item/clothing/head/helmet/unathi/hegemony(src)
	new /obj/item/clothing/head/helmet/unathi/hegemony(src)
	new /obj/item/clothing/head/helmet/unathi/hegemony(src)
	new /obj/item/clothing/head/helmet/unathi/hegemony(src)
	new /obj/item/clothing/head/helmet/unathi/klax(src)
	new /obj/item/clothing/suit/armor/unathi/hegemony(src)
	new /obj/item/clothing/suit/armor/unathi/hegemony(src)
	new /obj/item/clothing/suit/armor/unathi/hegemony(src)
	new /obj/item/clothing/suit/armor/unathi/hegemony(src)
	new /obj/item/clothing/suit/armor/unathi/klax(src)

/obj/structure/closet/crate/secure/gear_loadout/kataphract/single/fill()
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/head/helmet/space/void/kataphract(src)
	new /obj/item/clothing/suit/space/void/kataphract(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/melee/hammer/powered/hegemony(src)
	new /obj/item/melee/energy/sword/hegemony(src)
	new /obj/item/shield/energy/hegemony/kataphract(src)
	new /obj/item/clothing/head/helmet/unathi/hegemony(src)
	new /obj/item/clothing/suit/armor/unathi/hegemony(src)

/obj/structure/closet/crate/secure/gear_loadout/unathi_pirate/fill()
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/head/helmet/space/void/unathi_pirate(src)
	new /obj/item/clothing/suit/space/void/unathi_pirate(src)
	new /obj/item/clothing/head/helmet/space/void/unathi_pirate(src)
	new /obj/item/clothing/suit/space/void/unathi_pirate(src)
	new /obj/item/clothing/head/helmet/space/void/unathi_pirate(src)
	new /obj/item/clothing/suit/space/void/unathi_pirate(src)
	new /obj/item/clothing/head/helmet/space/void/unathi_pirate/captain(src)
	new /obj/item/clothing/suit/space/void/unathi_pirate/captain(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/gun/projectile/shotgun/pump/combat(src)
	new /obj/item/gun/projectile/automatic/rifle/sts35(src)
	new /obj/item/gun/energy/rifle/hegemony(src)
	new /obj/item/gun/projectile/automatic/rifle/dpra/gold(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/storage/box/shotgunshells(src)
	new /obj/item/storage/box/shotgunshells(src)
	new /obj/item/gun/energy/pistol/hegemony(src)
	new /obj/item/gun/projectile/colt/super(src)
	new /obj/item/gun/projectile/revolver/lemat(src)
	new /obj/item/ammo_magazine/c38(src)
	new /obj/item/ammo_magazine/c38(src)
	new /obj/item/ammo_magazine/c45m(src)
	new /obj/item/ammo_magazine/c45m(src)
	new /obj/item/storage/box/tarwa(src)
	new /obj/item/storage/box/kazu(src)
	new /obj/item/storage/box/hiskyn(src)

/obj/structure/closet/crate/secure/gear_loadout/unathi_pirate/single/fill()
	new /obj/item/clothing/under/unathi(src)
	new /obj/item/clothing/head/helmet/space/void/unathi_pirate(src)
	new /obj/item/clothing/suit/space/void/unathi_pirate(src)
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/clothing/glasses/eyepatch(src)
	new /obj/item/gun/projectile/revolver/lemat(src)
	new /obj/item/gun/projectile/shotgun/pump/combat(src)
	new /obj/item/ammo_magazine/c38(src)
	new /obj/item/ammo_magazine/c38(src)
	new /obj/item/storage/box/shotgunshells(src)
	new /obj/item/storage/box/shotgunshells(src)
	new /obj/item/voidsuit_modkit/tarwa(src)
	new /obj/item/voidsuit_modkit/kazu(src)
	new /obj/item/voidsuit_modkit/hiskyn(src)

/obj/structure/closet/crate/secure/gear_loadout/pvsm/fill()
	new /obj/item/clothing/under/tajaran/pvsm(src)
	new /obj/item/clothing/shoes/tajara/jackboots(src)
	new /obj/item/clothing/under/tajaran/pvsm(src)
	new /obj/item/clothing/shoes/tajara/jackboots(src)
	new /obj/item/clothing/under/tajaran/pvsm(src)
	new /obj/item/clothing/shoes/tajara/jackboots(src)
	new /obj/item/clothing/under/tajaran/pvsm/captain(src)
	new /obj/item/clothing/shoes/tajara/jackboots(src)
	new /obj/item/clothing/head/beret/tajaran/pvsm(src)
	new /obj/item/clothing/suit/space/void/dpra(src)
	new /obj/item/clothing/head/helmet/space/void/dpra(src)
	new /obj/item/clothing/suit/space/void/dpra(src)
	new /obj/item/clothing/head/helmet/space/void/dpra(src)
	new /obj/item/clothing/suit/space/void/dpra(src)
	new /obj/item/clothing/head/helmet/space/void/dpra(src)
	new /obj/item/clothing/suit/space/void/dpra(src)
	new /obj/item/clothing/head/helmet/space/void/dpra(src)
	new /obj/item/gun/projectile/automatic/rifle/dpra(src)
	new /obj/item/gun/projectile/automatic/rifle/dpra(src)
	new /obj/item/gun/projectile/automatic/rifle/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/gun/projectile/shotgun/pump/rifle/scope(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/ammo_magazine/boltaction(src)
	new /obj/item/gun/projectile/silenced(src)
	new /obj/item/ammo_magazine/c45m(src)
	new /obj/item/gun/projectile/silenced(src)
	new /obj/item/ammo_magazine/c45m(src)
	new /obj/item/gun/projectile/silenced(src)
	new /obj/item/ammo_magazine/c45m(src)
	new /obj/item/gun/projectile/silenced(src)
	new /obj/item/ammo_magazine/c45m(src)
	new /obj/item/gun/projectile/recoilless_rifle(src)
	new /obj/item/ammo_casing/recoilless_rifle(src)
	new /obj/item/ammo_casing/recoilless_rifle(src)

/obj/structure/closet/crate/secure/gear_loadout/pvsm/single/fill()
	new /obj/item/clothing/under/tajaran/pvsm(src)
	new /obj/item/clothing/shoes/tajara/jackboots(src)
	new /obj/item/clothing/suit/space/void/dpra(src)
	new /obj/item/clothing/head/helmet/space/void/dpra(src)
	new /obj/item/gun/projectile/automatic/rifle/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/ammo_magazine/c762/dpra(src)
	new /obj/item/material/knife/bayonet(src)
	new /obj/item/gun/projectile/silenced(src)
	new /obj/item/ammo_magazine/c45m(src)
	new /obj/item/ammo_magazine/c45m(src)

//ninja stuff
/obj/structure/closet/crate/secure/gear_loadout/ninja
	var/associated_hardsuit = /obj/item/rig/light/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/fill()
	new associated_hardsuit(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/stealth/fill()
	..()
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/silencer(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/sol
	associated_hardsuit = /obj/item/rig/military/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/sol/fill()
	..()
	new /obj/item/clothing/under/rank/sol/marine(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/gunslinger
	associated_hardsuit = /obj/item/rig/gunslinger/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/gunslinger/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/revolver/detective(src)
	new /obj/item/ammo_magazine/c38(src)
	new /obj/item/ammo_magazine/c38(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/breacher
	associated_hardsuit = /obj/item/rig/unathi/fancy/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/breacher/fill()
	..()
	new /obj/item/gun/energy/pistol/hegemony(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/tesla
	associated_hardsuit = /obj/item/rig/tesla/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/tesla/fill()
	..()
	new /obj/item/device/augment_implanter/advanced_tesla(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol/adhomai(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/strike
	associated_hardsuit = /obj/item/rig/strike/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/strike/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/automatic/x9(src)
	new /obj/item/ammo_magazine/c45m/auto(src)
	new /obj/item/ammo_magazine/c45m/auto(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/jinxiang
	associated_hardsuit = /obj/item/rig/jinxiang/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/jinxiang/fill()
	..()
	new /obj/item/melee/energy/sword/pirate(src)
	new /obj/item/shield/energy/dominia(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/tanto(src)
	new /obj/item/ammo_magazine/mc10mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/elyra
	associated_hardsuit = /obj/item/rig/elyran/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/elyra/fill()
	..()
	new /obj/item/gun/projectile/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/hacker
	associated_hardsuit = /obj/item/rig/light/hacker/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/hacker/fill()
	..()
	new /obj/item/gun/energy/xray(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/energy/crossbow/largecrossbow(src)
	new /obj/item/melee/energy/sword/red(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/frontier
	associated_hardsuit = /obj/item/rig/light/offworlder/frontier/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/frontier/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/crimson
	associated_hardsuit = /obj/item/rig/merc/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/crimson/fill()
	..()
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/revolver(src)
	new /obj/item/ammo_magazine/a357(src)
	new /obj/item/ammo_magazine/a357(src)

/obj/structure/closet/crate/secure/gear_loadout/ninja/rhino
	associated_hardsuit = /obj/item/rig/merc/distress/ninja

/obj/structure/closet/crate/secure/gear_loadout/ninja/rhino/fill()
	..()
	new /obj/item/gun/projectile/automatic/rifle/sts35(src)
	new /obj/item/ammo_magazine/c762(src)
	new /obj/item/clothing/accessory/holster/armpit/brown(src)
	new /obj/item/gun/projectile/pistol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
