/obj/structure/closet/crate/secure/gear_loadout
	desc = "A secure gear crate."
	name = "gear crate"
	req_access = list(access_syndicate)

/obj/structure/closet/crate/secure/gear_loadout/frontier/fill()
	new /obj/item/weapon/rig/gunslinger/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/frontier(src)
	new /obj/item/clothing/head/helmet/space/void/frontier(src)
	new /obj/item/clothing/head/helmet/space/void/frontier(src)
	new /obj/item/clothing/head/helmet/space/void/frontier(src)
	new /obj/item/clothing/head/helmet/space/void/frontier(src)
	new /obj/item/clothing/suit/space/void/frontier(src)
	new /obj/item/clothing/suit/space/void/frontier(src)
	new /obj/item/clothing/suit/space/void/frontier(src)
	new /obj/item/clothing/suit/space/void/frontier(src)
	new /obj/item/clothing/suit/space/void/frontier(src)
	new /obj/item/weapon/gun/projectile/revolver/mateba(src)
	new /obj/item/ammo_magazine/a454(src)
	new /obj/item/ammo_magazine/a454(src)
	new /obj/item/weapon/gun/energy/retro(src)
	new /obj/item/weapon/gun/energy/retro(src)
	new /obj/item/weapon/gun/projectile/gauss(src)
	new /obj/item/weapon/gun/projectile/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)

/obj/structure/closet/crate/secure/gear_loadout/frontier_single/fill()
	new /obj/item/clothing/head/helmet/space/void/frontier(src)
	new /obj/item/clothing/suit/space/void/frontier(src)
	new /obj/item/weapon/gun/projectile/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss(src)
	new /obj/item/ammo_magazine/gauss/emp(src)

/obj/structure/closet/crate/secure/gear_loadout/eridani/fill()
	new /obj/item/weapon/rig/strike/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/weapon/gun/energy/gun/nuclear(src)
	new /obj/item/weapon/gun/energy/gun/nuclear(src)
	new /obj/item/weapon/gun/energy/stunrevolver(src)
	new /obj/item/weapon/gun/energy/stunrevolver(src)
	new /obj/item/weapon/gun/energy/net(src)
	new /obj/item/weapon/gun/energy/lawgiver(src)

/obj/structure/closet/crate/secure/gear_loadout/eridani_single/fill()
	new /obj/item/clothing/head/helmet/space/void/cruiser(src)
	new /obj/item/clothing/suit/space/void/cruiser(src)
	new /obj/item/weapon/gun/energy/gun/nuclear(src)
	new /obj/item/weapon/gun/energy/stunrevolver(src)

/obj/structure/closet/crate/secure/gear_loadout/elyra/fill()
	new /obj/item/weapon/rig/elyran/equipped(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/weapon/gun/projectile/plasma(src)
	new /obj/item/weapon/gun/projectile/plasma(src)
	new /obj/item/weapon/gun/projectile/plasma/bolter(src)
	new /obj/item/weapon/gun/projectile/plasma/bolter(src)
	new /obj/item/weapon/gun/projectile/plasma/bolter(src)
	new /obj/item/weapon/gun/projectile/plasma/bolter(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/weapon/grenade/chem_grenade/large/phoroncleaner(src)
	new /obj/item/weapon/grenade/chem_grenade/large/phoroncleaner(src)

/obj/structure/closet/crate/secure/gear_loadout/elyra_single/fill()
	new /obj/item/clothing/head/helmet/space/void/valkyrie(src)
	new /obj/item/clothing/suit/space/void/valkyrie(src)
	new /obj/item/weapon/gun/projectile/plasma/bolter(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/ammo_magazine/plasma/light(src)
	new /obj/item/weapon/gun/projectile/pistol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/weapon/grenade/chem_grenade/large/phoroncleaner(src)

/obj/structure/closet/crate/secure/gear_loadout/sol/fill()
	new /obj/item/clothing/under/rank/fatigues/marine(src)
	new /obj/item/clothing/under/rank/fatigues/marine(src)
	new /obj/item/clothing/under/rank/fatigues/marine(src)
	new /obj/item/clothing/under/rank/fatigues/marine(src)
	new /obj/item/clothing/under/rank/fatigues/marine(src)
	new /obj/item/clothing/under/rank/fatigues/marine(src)
	new /obj/item/weapon/rig/military(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/weapon/gun/projectile/shotgun/pump/combat/sol(src)
	new /obj/item/ammo_magazine/assault_shotgun/shells(src)
	new /obj/item/weapon/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/weapon/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/weapon/gun/projectile/pistol/sol(src)
	new /obj/item/weapon/gun/projectile/pistol/sol(src)
	new /obj/item/weapon/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)
	new /obj/item/ammo_magazine/mc9mm(src)

/obj/structure/closet/crate/secure/gear_loadout/sol_single/fill()
	new /obj/item/clothing/under/rank/fatigues/marine(src)
	new /obj/item/clothing/head/helmet/space/void/sol(src)
	new /obj/item/clothing/suit/space/void/sol(src)
	new /obj/item/weapon/gun/projectile/automatic/rifle/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/ammo_magazine/c762/sol(src)
	new /obj/item/weapon/gun/projectile/pistol/sol(src)
	new /obj/item/ammo_magazine/mc9mm(src)
