#define CHANNEL_COMMON "Common"
#define CHANNEL_ENTERTAINMENT "Entertainment"
#define CHANNEL_HAILING	"Hailing"
#define CHANNEL_COMMAND "Command"
#define CHANNEL_SCIENCE "Science"
#define CHANNEL_MEDICAL "Medical"
#define CHANNEL_ENGINEERING "Engineering"
#define CHANNEL_SECURITY "Security"
#define CHANNEL_SUPPLY "Operations"
#define CHANNEL_SERVICE "Service"
#define CHANNEL_AI_PRIVATE "AI Private"
#define CHANNEL_PENAL "Penal"

#define CHANNEL_RESPONSE_TEAM "Response Team"

#define CHANNEL_RAIDER "Raider"
#define CHANNEL_MERCENARY "Mercenary"
#define CHANNEL_NINJA "Ninja"
#define CHANNEL_BLUESPACE "Bluespace"
#define CHANNEL_BURGLAR "Burglar"

var/global/list/ALL_RADIO_CHANNELS = list(
	CHANNEL_COMMON = TRUE,
	CHANNEL_ENTERTAINMENT = TRUE,
	CHANNEL_HAILING = TRUE,
	CHANNEL_COMMAND = TRUE,
	CHANNEL_SCIENCE = TRUE,
	CHANNEL_MEDICAL = TRUE,
	CHANNEL_ENGINEERING = TRUE,
	CHANNEL_SECURITY = TRUE,
	CHANNEL_SUPPLY = TRUE,
	CHANNEL_SERVICE = TRUE,
	CHANNEL_AI_PRIVATE = TRUE,
	CHANNEL_PENAL = TRUE,
	CHANNEL_RESPONSE_TEAM = TRUE,
	CHANNEL_RAIDER = TRUE,
	CHANNEL_MERCENARY = TRUE,
	CHANNEL_NINJA = TRUE,
	CHANNEL_BLUESPACE = TRUE,
	CHANNEL_BURGLAR = TRUE
	)
