/**
 * Drobes
 */

/obj/machinery/vending/wardrobe
	name = "Drobe - PARENT DO NOT USE"
	random_itemcount = FALSE
	restock_items = TRUE

/obj/machinery/vending/wardrobe/engi_wardrobe
	name = "\improper EngiDrobe"
	desc = "A vending machine renowned for vending industrial grade clothing."
	icon_state = "engidrobe"
	icon_deny = "engidrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Guaranteed* to protect against industrial accidents! (*not guaranteed);Yellow is the most radiation-resistant color!;Hi-viz is in this year! No, really!;You're the smartest department on the ship, so dress like it!"
	vend_reply = "Thank you for using EngiDrobe!"
	products = list(
		/obj/item/clothing/under/rank/engineer/apprentice/heph = 2,
		/obj/item/clothing/under/rank/engineer/apprentice/zavod = 2,
		/obj/item/clothing/under/rank/engineer/heph = 4,
		/obj/item/clothing/under/rank/engineer/zavod = 4,
		/obj/item/clothing/suit/storage/hazardvest = 5,
		/obj/item/clothing/suit/storage/hazardvest/green = 2,
		/obj/item/clothing/suit/storage/hazardvest/red = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/engineering = 8,
		/obj/item/clothing/suit/storage/hooded/wintercoat/heph = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/engi_dep_jacket = 8,
		/obj/item/clothing/suit/storage/toggle/corp/heph = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/highvis = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_alt = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_orange = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_red = 5,
		/obj/item/clothing/suit/storage/toggle/labcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/zavodskoi = 2,
		/obj/item/clothing/accessory/poncho/roles/engineering = 5,
		/obj/item/clothing/glasses/safety/goggles = 6,
		/obj/item/clothing/head/bandana/engineering = 4,
		/obj/item/clothing/head/beret/engineering = 4,
		/obj/item/clothing/head/beret/corporate/heph = 3,
		/obj/item/clothing/head/beret/corporate/zavod = 2,
		/obj/item/clothing/head/beret/corporate/zavod/alt = 2,
		/obj/item/clothing/head/hardhat/green = 2,
		/obj/item/clothing/head/hardhat/orange = 4,
		/obj/item/clothing/head/hardhat/red = 2,
		/obj/item/clothing/head/sidecap/heph = 3,
		/obj/item/clothing/head/sidecap/zavod = 3,
		/obj/item/clothing/head/sidecap/zavod/alt = 3,
		/obj/item/clothing/head/softcap/engineering = 4,
		/obj/item/clothing/head/softcap/zavod = 2,
		/obj/item/clothing/head/softcap/zavod/alt = 2,
		/obj/item/clothing/head/wool/heph = 4,
		/obj/item/clothing/head/wool/zavod = 2,
		/obj/item/clothing/head/wool/zavod/alt = 2,
		/obj/item/clothing/accessory/storage/overalls/engineer = 4,
		/obj/item/clothing/pants/highvis = 5,
		/obj/item/clothing/pants/highvis_alt = 5,
		/obj/item/clothing/pants/highvis_orange = 5,
		/obj/item/clothing/pants/highvis_red = 5,
		/obj/item/clothing/shoes/sneakers/orange = 6,
		/obj/item/clothing/shoes/workboots/dark = 6,
		/obj/item/clothing/shoes/workboots/toeless = 4,
		/obj/item/storage/backpack/industrial = 6,
		/obj/item/storage/backpack/heph = 4,
		/obj/item/storage/backpack/zavod = 4,
		/obj/item/storage/backpack/duffel/eng = 6,
		/obj/item/storage/backpack/duffel/heph = 4,
		/obj/item/storage/backpack/duffel/zavod = 4,
		/obj/item/storage/backpack/cloak/engi = 3,
		/obj/item/storage/backpack/cloak/heph = 2,
		/obj/item/storage/backpack/cloak/zavod = 2
	)
	premium = list(
		/obj/item/toy/figure/engineer = 6,
		/obj/item/toy/figure/ce = 2
	)
	contraband = list(
		/obj/item/clothing/under/rank/engineer/einstein = 4
	)
	light_color = COLOR_GOLD

/obj/machinery/vending/wardrobe/atmos_wardrobe
	name = "\improper AtmosDrobe"
	desc = "This relatively unknown vending machine delivers clothing for Atmospherics Technicians, an equally unknown job."
	icon_state = "atmosdrobe"
	icon_deny = "atmosdrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Flammable? Inflammable? Doesn't matter!;If you know the Ideal Gas constant, show it off with these clothes!;Show up those pitiful engineers with stylish blue trim today!;Long live Atmosia! Gloria Admosia!"
	vend_reply = "Thank you for using Atmosdrobe!"
	products = list(
		/obj/item/clothing/under/rank/atmospheric_technician/heph = 2,
		/obj/item/clothing/under/rank/atmospheric_technician/zavod = 2,
		/obj/item/clothing/suit/storage/hazardvest/blue/atmos = 3,
		/obj/item/clothing/suit/storage/hazardvest/green = 2,
		/obj/item/clothing/suit/storage/hazardvest/red = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/engineering/atmos = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/heph = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/engi_dep_jacket = 4,
		/obj/item/clothing/suit/storage/toggle/corp/heph = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/highvis = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_alt = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_orange = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_red = 3,
		/obj/item/clothing/suit/storage/toggle/labcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/zavodskoi = 2,
		/obj/item/clothing/accessory/poncho/roles/engineering = 3,
		/obj/item/clothing/pants/highvis = 3,
		/obj/item/clothing/pants/highvis_alt = 3,
		/obj/item/clothing/pants/highvis_orange = 3,
		/obj/item/clothing/pants/highvis_red = 3,
		/obj/item/clothing/glasses/safety/goggles = 3,
		/obj/item/clothing/head/bandana/atmos = 2,
		/obj/item/clothing/head/beret/atmos = 2,
		/obj/item/clothing/head/beret/corporate/heph = 3,
		/obj/item/clothing/head/beret/corporate/zavod = 2,
		/obj/item/clothing/head/beret/corporate/zavod/alt = 2,
		/obj/item/clothing/head/hardhat/orange = 2,
		/obj/item/clothing/head/hardhat/green = 2,
		/obj/item/clothing/head/hardhat/red = 2,
		/obj/item/clothing/head/sidecap/zavod = 3,
		/obj/item/clothing/head/sidecap/zavod/alt = 3,
		/obj/item/clothing/head/softcap/atmos = 2,
		/obj/item/clothing/head/softcap/zavod = 2,
		/obj/item/clothing/head/softcap/zavod/alt = 2,
		/obj/item/clothing/head/wool/heph = 4,
		/obj/item/clothing/head/wool/zavod = 2,
		/obj/item/clothing/head/wool/zavod/alt = 2,
		/obj/item/clothing/accessory/storage/overalls/engineer = 3,
		/obj/item/clothing/shoes/sneakers/orange = 4,
		/obj/item/clothing/shoes/workboots/dark = 4,
		/obj/item/clothing/shoes/workboots/toeless = 2,
		/obj/item/storage/backpack/industrial = 6,
		/obj/item/storage/backpack/heph = 4,
		/obj/item/storage/backpack/zavod = 4,
		/obj/item/storage/backpack/duffel/eng = 6,
		/obj/item/storage/backpack/duffel/heph = 4,
		/obj/item/storage/backpack/duffel/zavod = 4,
		/obj/item/storage/backpack/cloak/engi = 3,
		/obj/item/storage/backpack/cloak/heph = 2,
		/obj/item/storage/backpack/cloak/zavod = 2
	)
	premium = list(
		/obj/item/toy/figure/atmos = 3,
		/obj/item/toy/figure/ce = 2
	)
	contraband = list(
		/obj/item/clothing/under/rank/engineer/einstein = 4
	)
	light_color = COLOR_GOLD

/obj/machinery/vending/wardrobe/sec_wardrobe
	name = "\improper SecDrobe"
	desc = "A vending machine for security and security-related clothing!"
	icon_state = "secdrobe"
	icon_deny = "secdrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Beat perps in style!;You have the right to be fashionable!;Now you can be the fashion police you always wanted to be!;Blood on your uniform? Don't wash it out, get a 	one!;Be more than a mall cop!"
	vend_reply = "Thank you for using SecDrobe!"
	products = list(
		/obj/item/clothing/under/rank/cadet = 4,
		/obj/item/clothing/under/rank/cadet/idris = 3,
		/obj/item/clothing/under/rank/cadet/pmc = 3,
		/obj/item/clothing/under/rank/cadet/zavod = 3,
		/obj/item/clothing/under/rank/security = 4,
		/obj/item/clothing/under/rank/security/idris = 3,
		/obj/item/clothing/under/rank/security/idris/idrissec = 3,
		/obj/item/clothing/under/rank/security/idris/idrissec/alt = 3,
		/obj/item/clothing/under/rank/security/pmc = 3,
		/obj/item/clothing/under/rank/security/pmc/pmcsec = 3,
		/obj/item/clothing/under/rank/security/pmc/pmcsec/alt = 3,
		/obj/item/clothing/under/rank/security/zavod = 3,
		/obj/item/clothing/under/rank/security/zavod/zavodsec = 3,
		/obj/item/clothing/under/rank/security/zavod/zavodsec/alt = 3,
		/obj/item/clothing/under/det = 2,
		/obj/item/clothing/under/det/idris = 2,
		/obj/item/clothing/under/det/idris/alt = 2,
		/obj/item/clothing/under/det/pmc = 2,
		/obj/item/clothing/under/det/pmc/alt = 2,
		/obj/item/clothing/under/det/zavod = 2,
		/obj/item/clothing/under/det/zavod/alt = 2,
		/obj/item/clothing/under/rank/warden = 2,
		/obj/item/clothing/under/rank/warden/idris = 2,
		/obj/item/clothing/under/rank/warden/pmc = 2,
		/obj/item/clothing/under/rank/warden/zavod = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/security = 8,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/pmc = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod/alt = 4,
		/obj/item/clothing/suit/storage/security/officer/idris = 2,
		/obj/item/clothing/suit/storage/security/officer/idris/alt = 2,
		/obj/item/clothing/suit/storage/security/officer/pmc = 4,
		/obj/item/clothing/suit/storage/security/officer/zav = 2,
		/obj/item/clothing/suit/storage/security/officer/zav/alt = 2,
		/obj/item/clothing/suit/storage/security/investigator = 2,
		/obj/item/clothing/suit/storage/security/investigator/idris = 2,
		/obj/item/clothing/suit/storage/security/investigator/pmc = 2,
		/obj/item/clothing/suit/storage/security/investigator/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/warden = 2,
		/obj/item/clothing/suit/storage/toggle/warden/idris = 2,
		/obj/item/clothing/suit/storage/toggle/warden/pmc = 2,
		/obj/item/clothing/suit/storage/toggle/warden/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/warden/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/idris = 2,
		/obj/item/clothing/suit/storage/toggle/corp/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/pmc = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/alt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/pmc = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/pmc/alt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/alt = 4,
		/obj/item/clothing/suit/storage/toggle/longcoat/idris = 4,
		/obj/item/clothing/suit/storage/toggle/longcoat/pmc = 4,
		/obj/item/clothing/suit/storage/toggle/longcoat/zavodskoi = 4,
		/obj/item/clothing/suit/storage/toggle/sec_dep_jacket = 8,
		/obj/item/clothing/accessory/holster/waist = 8,
		/obj/item/clothing/gloves/black_leather = 8,
		/obj/item/clothing/mask/balaclava = 4,
		/obj/item/clothing/head/bandana/security = 8,
		/obj/item/clothing/head/beret/security = 4,
		/obj/item/clothing/head/beret/security/officer = 4,
		/obj/item/clothing/head/beret/corporate/idris = 4,
		/obj/item/clothing/head/beret/corporate/idris/alt = 4,
		/obj/item/clothing/head/beret/corporate/zavod = 4,
		/obj/item/clothing/head/beret/corporate/zavod/alt = 4,
		/obj/item/clothing/head/peaked_cap/idris = 4,
		/obj/item/clothing/head/peaked_cap/idris/no_logo = 4,
		/obj/item/clothing/head/sidecap/pmcg = 4,
		/obj/item/clothing/head/sidecap/zavod = 4,
		/obj/item/clothing/head/sidecap/zavod/alt = 4,
		/obj/item/clothing/head/softcap/security = 8,
		/obj/item/clothing/head/softcap/idris = 4,
		/obj/item/clothing/head/softcap/idris/alt = 4,
		/obj/item/clothing/head/softcap/pmc = 4,
		/obj/item/clothing/head/softcap/zavod = 4,
		/obj/item/clothing/head/softcap/zavod/alt = 4,
		/obj/item/clothing/head/warden = 2,
		/obj/item/clothing/head/warden/idris = 2,
		/obj/item/clothing/head/warden/pmc = 2,
		/obj/item/clothing/head/warden/zavod = 2,
		/obj/item/clothing/head/warden/zavod/alt = 2,
		/obj/item/clothing/head/wool/idris = 4,
		/obj/item/clothing/head/wool/idris/alt = 4,
		/obj/item/clothing/head/wool/pmc = 4,
		/obj/item/clothing/head/wool/zavod = 4,
		/obj/item/clothing/head/wool/zavod/alt = 4,
		/obj/item/clothing/shoes/laceup = 2,
		/obj/item/clothing/shoes/jackboots = 8,
		/obj/item/clothing/shoes/jackboots/toeless = 6,
		/obj/item/storage/backpack/security = 6,
		/obj/item/storage/backpack/idris = 4,
		/obj/item/storage/backpack/pmcg = 4,
		/obj/item/storage/backpack/zavod = 4,
		/obj/item/storage/backpack/duffel/sec = 6,
		/obj/item/storage/backpack/duffel/idris = 4,
		/obj/item/storage/backpack/duffel/pmcg = 4,
		/obj/item/storage/backpack/duffel/zavod = 4,
		/obj/item/storage/backpack/cloak/phalanx = 2,
		/obj/item/storage/backpack/cloak/sec = 2,
		/obj/item/storage/backpack/cloak/zavod = 2
	)
	premium = list(
		/obj/item/toy/figure/secofficer = 6,
		/obj/item/toy/figure/detective = 2,
		/obj/item/toy/figure/warden = 2,
		/obj/item/toy/figure/hos = 2,
		/obj/item/clothing/accessory/storage/bayonet = 4
	)
	contraband = list(
		/obj/item/clothing/under/rank/security/einstein = 4
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/bar_wardrobe
	name = "BarDrobe"
	desc = "A stylish vendor to dispense the most stylish bar clothing!"
	icon_state = "bardrobe"
	icon_deny = "bardrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Now 12% more stain-resistant!;Better-dressed bartenders get better tips! Hint hint!;Let's class this joint up! Or down, your call!;How's it feel to be the coolest part of the Service department?"
	vend_reply = "Thank you for using the BarDrobe!"
	products = list(
		/obj/item/clothing/under/sl_suit = 3,
		/obj/item/clothing/under/rank/bartender = 3,
		/obj/item/clothing/under/suit_jacket = 3,
		/obj/item/clothing/under/suit_jacket/burgundy = 3,
		/obj/item/clothing/under/suit_jacket/navy = 3,
		/obj/item/clothing/under/suit_jacket/really_black = 3,
		/obj/item/clothing/under/suit_jacket/red = 3,
		/obj/item/clothing/suit/storage/bartender = 3,
		/obj/item/clothing/suit/storage/bartender/idris = 3,
		/obj/item/clothing/suit/storage/bartender/orion = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/nt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion/alt = 2,
		/obj/item/clothing/accessory/wcoat = 3,
		/obj/item/clothing/head/bowler = 3,
		/obj/item/clothing/head/flatcap/bartender = 3,
		/obj/item/clothing/head/flatcap/bartender/idris = 3,
		/obj/item/clothing/head/flatcap/bartender/orion = 3,
		/obj/item/clothing/head/pin/flower = 3,
		/obj/item/clothing/head/pin/flower/blue = 3,
		/obj/item/clothing/head/pin/flower/pink = 3,
		/obj/item/clothing/head/pin/flower/yellow = 3,
		/obj/item/clothing/head/pin/magnetic = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/clothing/head/softcap/nt = 3,
		/obj/item/clothing/head/softcap/orion = 3,
		/obj/item/clothing/head/wool/idris = 3,
		/obj/item/clothing/head/wool/idris/alt = 3,
		/obj/item/clothing/head/wool/nt = 3,
		/obj/item/clothing/head/wool/orion = 3,
		/obj/item/clothing/head/wool/orion/alt = 3,
		/obj/item/clothing/head/top_hat = 3,
		/obj/item/clothing/shoes/laceup = 3,
		/obj/item/clothing/shoes/laceup/grey = 3,
		/obj/item/clothing/shoes/sneakers/black = 3,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
		/obj/item/storage/backpack/cloak/orion = 2
	)
	premium = list(
		/obj/item/toy/figure/bartender = 3,
		/obj/item/clothing/accessory/storage/bandolier = 2,
		/obj/item/clothing/head/bearpelt = 2,
		/obj/item/clothing/head/cowboy = 2,
		/obj/item/clothing/head/fez = 2,
		/obj/item/clothing/glasses/monocle = 2
	)
	contraband = list(
		/obj/item/clothing/head/welding = 2
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/chef_wardrobe
	name = "ChefDrobe"
	desc = "This vending machine might not dispense food, but it certainly dispenses chef-related clothing."
	icon_state = "chefdrobe"
	icon_deny = "chefdrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Now 17% more stain-resistant!;Won't make your food taste any better, but you'll look good!;The taller the hat, the better the chef.;Did you leave something on the stove?;About time you got some sweet fit!"
	vend_reply = "Thank you for using the ChefDrobe!"
	products = list(
		/obj/item/clothing/under/rank/chef = 3,
		/obj/item/clothing/under/rank/chef/idris = 3,
		/obj/item/clothing/under/rank/chef/orion = 3,
		/obj/item/clothing/under/waiter = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/nt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion/alt = 2,
		/obj/item/clothing/accessory/wcoat = 3,
		/obj/item/clothing/head/hairnet = 3,
		/obj/item/clothing/head/chefhat = 3,
		/obj/item/clothing/head/chefhat/nt = 3,
		/obj/item/clothing/head/chefhat/idris = 3,
		/obj/item/clothing/head/chefhat/orion = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/clothing/head/softcap/nt = 3,
		/obj/item/clothing/head/softcap/orion = 3,
		/obj/item/clothing/head/wool/idris = 3,
		/obj/item/clothing/head/wool/idris/alt = 3,
		/obj/item/clothing/head/wool/nt = 3,
		/obj/item/clothing/head/wool/orion = 3,
		/obj/item/clothing/head/wool/orion/alt = 3,
		/obj/item/storage/box/gloves = 3,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/storage/backpack/cloak/orion = 2
	)
	premium = list(
		/obj/item/toy/figure/chef = 3
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/jani_wardrobe
	name = "JaniDrobe"
	desc = "A self-cleaning vending machine capable of dispensing clothing for janitors."
	icon_state = "janidrobe"
	icon_deny = "janidrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Now endorsed by lizard janitors everywhere!;Proudly represent Janitor Nation!;Don't worry, purple is in this season!;Clothes covered in hydraulic fluid and blood? Get some 	ones!;Fuck the haters. You look great."
	vend_reply = "Thank you for using JaniDrobe!"
	products = list(
		/obj/item/clothing/under/rank/janitor = 3,
		/obj/item/clothing/under/rank/janitor/alt = 3,
		/obj/item/clothing/under/rank/janitor/idris = 3,
		/obj/item/clothing/under/rank/janitor/idris/alt = 3,
		/obj/item/clothing/under/rank/janitor/orion = 3,
		/obj/item/clothing/suit/caution = 6,
		/obj/item/clothing/suit/storage/hazardvest = 5,
		/obj/item/clothing/suit/storage/hazardvest/purple = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/nt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion/alt = 2,
		/obj/item/clothing/suit/storage/toggle/highvis = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_alt = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_orange = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_red = 5,
		/obj/item/storage/belt/custodial = 3,
		/obj/item/clothing/accessory/holster/utility/custodial/armpit = 2,
		/obj/item/clothing/accessory/holster/utility/custodial/hip = 2,
		/obj/item/clothing/pants/highvis = 3,
		/obj/item/clothing/pants/highvis_alt = 3,
		/obj/item/clothing/pants/highvis_orange = 3,
		/obj/item/clothing/pants/highvis_red = 3,
		/obj/item/clothing/head/bandana/janitor = 3,
		/obj/item/clothing/head/beret/janitor = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/clothing/head/softcap/idris/custodian = 3,
		/obj/item/clothing/head/softcap/nt = 3,
		/obj/item/clothing/head/softcap/nt/custodian = 3,
		/obj/item/clothing/head/softcap/orion = 3,
		/obj/item/clothing/head/wool/idris = 3,
		/obj/item/clothing/head/wool/idris/alt = 3,
		/obj/item/clothing/head/wool/nt = 3,
		/obj/item/clothing/head/wool/orion = 3,
		/obj/item/clothing/head/wool/orion/alt = 3,
		/obj/item/clothing/gloves/janitor = 4,
		/obj/item/clothing/gloves/janitor/tajara = 2,
		/obj/item/clothing/gloves/janitor/unathi = 2,
		/obj/item/clothing/gloves/janitor/vaurca = 2,
		/obj/item/clothing/glasses/safety/goggles = 6,
		/obj/item/clothing/shoes/galoshes = 4,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/storage/backpack/cloak/orion = 2
	)
	premium = list(
		/obj/item/toy/figure/janitor = 6
	)
	light_color = COLOR_LIME

/obj/machinery/vending/wardrobe/hydro_wardrobe
	name = "HyDrobe"
	desc = "A machine with a catchy name. It dispenses botany-related clothing and gear."
	icon_state = "hydrobe"
	icon_deny = "hydrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Do you love soil? Then buy our clothes!;Get outfits to match your green thumb here!;Soil resistant! Or absorbant! Who cares!;Guaranteed-ish to make plants grow faster if you wear it!;Can you hear them speaking too?"
	vend_reply = "Thank you for using HyDrobe!"
	products = list(
		/obj/item/clothing/under/rank/hydroponics = 4,
		/obj/item/clothing/under/rank/hydroponics/idris = 2,
		/obj/item/clothing/under/rank/hydroponics/orion = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/hydro = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/nt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion = 2,
		/obj/item/clothing/suit/storage/toggle/corp/orion/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/nt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/orion = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/idris = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/nt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/orion = 2,
		/obj/item/clothing/head/bandana/hydro = 3,
		/obj/item/clothing/head/bandana/hydro/idris = 3,
		/obj/item/clothing/head/bandana/hydro/nt = 3,
		/obj/item/clothing/head/bandana/hydro/orion = 3,
		/obj/item/clothing/head/beret/hydro = 3,
		/obj/item/clothing/head/softcap/hydro = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/clothing/head/softcap/idris/custodian = 3,
		/obj/item/clothing/head/softcap/nt = 3,
		/obj/item/clothing/head/softcap/nt/custodian = 3,
		/obj/item/clothing/head/softcap/orion = 3,
		/obj/item/clothing/head/wool/idris = 3,
		/obj/item/clothing/head/wool/idris/alt = 3,
		/obj/item/clothing/head/wool/nt = 3,
		/obj/item/clothing/head/wool/orion = 3,
		/obj/item/clothing/head/wool/orion/alt = 3,
		/obj/item/clothing/accessory/apron/blue = 3,
		/obj/item/clothing/accessory/overalls/blue = 3,
		/obj/item/storage/backpack/hydroponics = 5,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/hyd = 5,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/storage/backpack/cloak/orion = 2
	)
	premium = list(
		/obj/item/toy/figure/gardener = 3
	)
	light_color = COLOR_LIME

/obj/machinery/vending/wardrobe/chap_wardrobe
	name = "ChapelDrobe"
	desc = "God wills your purchase."
	icon_state = "chapdrobe"
	icon_deny = "chapdrobe-deny"
	light_mask = "clothes-lightmask"
	product_ads = "Maybe they'd listen if you dressed better?;Clothes for people of the cloth!;No laity allowed!"
	vend_reply = "Thank you for using ChapelDrobe!"
	products = list(
		/obj/item/clothing/under/rank/chaplain = 3,
		/obj/item/clothing/under/tajaran/matake = 3,
		/obj/item/clothing/under/unathi/skakh = 2,
		/obj/item/clothing/under/unathi/skakh/fisher = 2,
		/obj/item/clothing/under/unathi/skakh/healer = 2,
		/obj/item/clothing/under/unathi/skakh/warrior = 2,
		/obj/item/clothing/suit/nun = 3,
		/obj/item/clothing/suit/storage/hooded/tajaran/priest = 2,
		/obj/item/clothing/suit/storage/tajaran/messa = 3,
		/obj/item/clothing/suit/storage/tajaran/matake = 2,
		/obj/item/clothing/suit/storage/tajaran/azubarre = 2,
		/obj/item/clothing/head/chaplain_hood = 3,
		/obj/item/clothing/head/nun_hood = 3,
		/obj/item/clothing/head/hijab = 3,
		/obj/item/clothing/head/turban = 3,
		/obj/item/clothing/head/kippah = 3,
		/obj/item/clothing/head/unathi/maxtlatl = 3,
		/obj/item/clothing/mask/trinary_mask = 3,
		/obj/item/clothing/mask/gas/unathi = 3,
		/obj/item/clothing/mask/tajara = 3,
		/obj/item/clothing/accessory/apron/dharmela = 2,
		/obj/item/clothing/shoes/sneakers/black = 3,
		/obj/item/storage/box/fancy/candle_box = 3,
		/obj/item/storage/box/fancy/candle_box = 3,
		/obj/item/deck/tarot = 3,
		/obj/item/deck/tarot/nralakk = 2,
		/obj/item/deck/tarot/nonnralakk = 2,
		/obj/item/deck/tarot/adhomai = 2,
		/obj/item/deck/lyodii = 2
	)
	contraband = list(
		/obj/item/clothing/suit/cultrobes/alt = 2,
		/obj/item/clothing/head/culthood/alt = 2,
		/obj/item/clothing/shoes/cult = 2,
		/obj/item/clothing/head/tajaran/raskara = 2,
		/obj/item/clothing/suit/storage/tajaran/raskara = 2
	)
	premium = list(
		/obj/item/toy/figure/chaplain = 3
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/science_wardrobe
	name = "SciDrobe"
	desc = "A simple vending machine suitable to dispense well-tailored science clothing."
	icon_state = "scidrobe"
	product_ads = "Surely nothing will go wrong!;Leave a pretty corpse!;Be remembered for your slick fashion sense!"
	vend_reply = "Thank you for using SciDrobe!"
	products = list(
		/obj/item/clothing/under/rank/scientist/intern = 3,
		/obj/item/clothing/under/rank/scientist/intern/zavod = 2,
		/obj/item/clothing/under/rank/scientist/intern/zeng = 2,
		/obj/item/clothing/under/rank/scientist = 6,
		/obj/item/clothing/under/rank/scientist/zavod = 3,
		/obj/item/clothing/under/rank/scientist/zeng = 3,
		/obj/item/clothing/under/rank/scientist/botany = 6,
		/obj/item/clothing/under/rank/scientist/botany/zavod = 3,
		/obj/item/clothing/under/rank/scientist/botany/zeng = 3,
		/obj/item/clothing/under/rank/scientist/xenobio = 6,
		/obj/item/clothing/under/rank/scientist/xenobio/zavod = 3,
		/obj/item/clothing/under/rank/scientist/xenobio/zeng = 3,
		/obj/item/clothing/under/rank/scientist/xenoarchaeologist = 6,
		/obj/item/clothing/under/rank/scientist/xenoarchaeologist/zavod = 3,
		/obj/item/clothing/under/rank/scientist/xenoarchaeologist/zeng = 3,
		/obj/item/clothing/under/rank/scientist/anomalist = 6,
		/obj/item/clothing/under/rank/scientist/anomalist/zavod = 3,
		/obj/item/clothing/under/rank/scientist/anomalist/zeng = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/science = 8,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 6,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod/alt = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zeng = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zeng/alt = 3,
		/obj/item/clothing/suit/storage/toggle/sci_dep_jacket = 6,
		/obj/item/clothing/suit/storage/toggle/corp/nt = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zeng = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zeng/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat = 6,
		/obj/item/clothing/suit/storage/toggle/labcoat/nt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zeng = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zeng/alt = 2,
		/obj/item/clothing/head/bandana/science = 8,
		/obj/item/clothing/head/beret/science = 6,
		/obj/item/clothing/head/beret/corporate/zavod = 3,
		/obj/item/clothing/head/beret/corporate/zavod/alt = 3,
		/obj/item/clothing/head/beret/corporate/zeng = 3,
		/obj/item/clothing/head/beret/corporate/zeng/alt = 3,
		/obj/item/clothing/head/softcap/science = 6,
		/obj/item/clothing/head/softcap/nt = 4,
		/obj/item/clothing/head/softcap/zavod = 3,
		/obj/item/clothing/head/softcap/zavod/alt = 3,
		/obj/item/clothing/head/softcap/zeng = 3,
		/obj/item/clothing/head/wool/nt = 6,
		/obj/item/clothing/head/wool/zeng = 3,
		/obj/item/clothing/head/wool/zeng/alt = 3,
		/obj/item/clothing/head/wool/zavod = 3,
		/obj/item/clothing/head/wool/zavod/alt = 3,
		/obj/item/clothing/accessory/poncho/roles/science = 8,
		/obj/item/clothing/shoes/sneakers/medsci = 8,
		/obj/item/clothing/shoes/sneakers/medsci/zavod = 4,
		/obj/item/clothing/shoes/sneakers/medsci/zeng = 4,
		/obj/item/storage/backpack/toxins = 8,
		/obj/item/storage/backpack/nt = 4,
		/obj/item/storage/backpack/zavod = 4,
		/obj/item/storage/backpack/zeng = 4,
		/obj/item/storage/backpack/duffel/tox = 8,
		/obj/item/storage/backpack/duffel/nt = 4,
		/obj/item/storage/backpack/duffel/zavod = 4,
		/obj/item/storage/backpack/duffel/zeng = 4,
		/obj/item/storage/backpack/cloak/sci = 4,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/storage/backpack/cloak/zavod = 2
	)
	contraband = list(
		/obj/item/clothing/under/rank/scientist/einstein = 4
	)
	premium = list(
		/obj/item/toy/figure/scientist = 8
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/medi_wardrobe
	name = "\improper MediDrobe"
	desc = "A vending machine rumoured to be capable of dispensing clothing for medical personnel."
	icon_state = "medidrobe"
	product_ads = "Blood is always a great accent color!;Look like you stepped right off the set of a med drama holo!;Save lives AND look good!"
	vend_reply = "Thank you for using MediDrobe!"
	products = list(
		/obj/item/clothing/under/rank/medical/intern = 3,
		/obj/item/clothing/under/rank/medical/intern/pmc/alt = 2,
		/obj/item/clothing/under/rank/medical/intern/zeng = 2,
		/obj/item/clothing/under/rank/medical = 6,
		/obj/item/clothing/under/rank/medical/pmc/alt = 3,
		/obj/item/clothing/under/rank/medical/pmc/nexus = 3,
		/obj/item/clothing/under/rank/medical/zeng = 3,
		/obj/item/clothing/under/rank/medical/paramedic = 2,
		/obj/item/clothing/under/rank/medical/paramedic/zeng = 2,
		/obj/item/clothing/under/rank/medical/paramedic/pmc = 2,
		/obj/item/clothing/under/rank/medical/paramedic/pmc/alt = 2,
		/obj/item/clothing/under/rank/medical/paramedic/pmc/epmc = 2,
		/obj/item/clothing/under/rank/medical/paramedic/pmc/nexus = 2,
		/obj/item/clothing/under/rank/medical/paramedic/pmc/sekh = 2,
		/obj/item/clothing/under/rank/medical/paramedic/pmc/vekatak_phalanx = 2,
		/obj/item/clothing/under/rank/medical/paramedic/zeng = 2,
		/obj/item/clothing/under/rank/medical/psych = 3,
		/obj/item/clothing/under/rank/medical/psych/pmc/alt = 2,
		/obj/item/clothing/under/rank/medical/psych/zeng = 2,
		/obj/item/clothing/under/rank/medical/surgeon = 3,
		/obj/item/clothing/under/rank/medical/surgeon/pmc/alt = 2,
		/obj/item/clothing/under/rank/medical/surgeon/zeng = 2,
		/obj/item/clothing/under/medical_gown = 6,
		/obj/item/clothing/under/medical_gown/white = 6,
		/obj/item/clothing/suit/storage/surgical_gown/nt = 3,
		/obj/item/clothing/suit/storage/surgical_gown/zeng = 3,
		/obj/item/clothing/suit/storage/surgical_gown/pmc/alt = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/medical = 6,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/pmc/alt = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zeng = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zeng/alt = 2,
		/obj/item/clothing/suit/storage/toggle/med_dep_jacket = 8,
		/obj/item/clothing/suit/storage/toggle/corp/nt = 4,
		/obj/item/clothing/suit/storage/toggle/corp/pmc/alt = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zeng = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zeng/alt = 2,
		/obj/item/clothing/suit/storage/toggle/para_jacket = 4,
		/obj/item/clothing/suit/storage/toggle/para_jacket/pmc = 2,
		/obj/item/clothing/suit/storage/toggle/para_jacket/zeng = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat = 8,
		/obj/item/clothing/suit/storage/toggle/labcoat/epmc = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/nexus = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/nt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zeng = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zeng/alt = 2,
		/obj/item/clothing/head/bandana/medical = 8,
		/obj/item/clothing/head/surgery = 4,
		/obj/item/clothing/head/surgery/generic = 2,
		/obj/item/clothing/head/surgery/zeng = 2,
		/obj/item/clothing/head/surgery/pmc/alt = 2,
		/obj/item/clothing/head/beret/medical = 8,
		/obj/item/clothing/head/beret/corporate/pmc/epmc = 4,
		/obj/item/clothing/head/beret/corporate/zeng = 2,
		/obj/item/clothing/head/beret/corporate/zeng/alt = 2,
		/obj/item/clothing/head/softcap/medical = 6,
		/obj/item/clothing/head/softcap/nt = 3,
		/obj/item/clothing/head/softcap/pmc/epmc = 3,
		/obj/item/clothing/head/softcap/zeng = 3,
		/obj/item/clothing/head/wool/nt = 4,
		/obj/item/clothing/head/wool/pmc/alt = 4,
		/obj/item/clothing/head/wool/zeng = 2,
		/obj/item/clothing/head/wool/zeng/alt = 2,
		/obj/item/clothing/head/hardhat/paramedic = 4,
		/obj/item/clothing/mask/surgical = 8,
		/obj/item/clothing/accessory/stethoscope = 8,
		/obj/item/clothing/accessory/poncho/roles/medical = 6,
		/obj/item/clothing/shoes/sneakers/black = 6,
		/obj/item/clothing/shoes/sneakers/medsci = 6,
		/obj/item/clothing/shoes/sneakers/medsci/pmc = 4,
		/obj/item/clothing/shoes/sneakers/medsci/zeng = 4,
		/obj/item/clothing/shoes/jackboots = 4,
		/obj/item/storage/backpack/medic = 8,
		/obj/item/storage/backpack/emt = 4,
		/obj/item/storage/backpack/psychiatrist = 2,
		/obj/item/storage/backpack/nt = 4,
		/obj/item/storage/backpack/pmcg = 4,
		/obj/item/storage/backpack/zeng = 4,
		/obj/item/storage/backpack/duffel/med = 8,
		/obj/item/storage/backpack/duffel/emt = 4,
		/obj/item/storage/backpack/duffel/psych = 2,
		/obj/item/storage/backpack/duffel/nt = 4,
		/obj/item/storage/backpack/duffel/pmcg = 4,
		/obj/item/storage/backpack/duffel/zeng = 4,
		/obj/item/storage/backpack/cloak/medical = 4,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/storage/backpack/cloak/phalanx = 2
	)
	premium = list(
		/obj/item/toy/figure/md = 6,
		/obj/item/toy/figure/paramedic = 4,
		/obj/item/toy/figure/psychologist = 2
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/chem_wardrobe
	name = "ChemDrobe"
	desc = "A vending machine for dispensing chemistry related clothing."
	icon_state = "chemdrobe"
	product_ads = "Now 0.5% more resistant to acid spills!;Forget meds, make napalm! Be cool!;Try our new grenade fannypacks!"
	vend_reply = "Thank you for using ChemDrobe!"
	products = list(
		/obj/item/clothing/under/rank/medical/pharmacist = 3,
		/obj/item/clothing/under/rank/medical/pharmacist/pmc/alt = 2,
		/obj/item/clothing/under/rank/medical/pharmacist/zeng = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/medical = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/pmc/alt = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zeng = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zeng/alt = 2,
		/obj/item/clothing/suit/storage/toggle/med_dep_jacket = 4,
		/obj/item/clothing/suit/storage/toggle/corp/nt = 3,
		/obj/item/clothing/suit/storage/toggle/corp/pmc/alt = 3,
		/obj/item/clothing/suit/storage/toggle/corp/zeng = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zeng/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/epmc = 3,
		/obj/item/clothing/suit/storage/toggle/labcoat/nexus = 3,
		/obj/item/clothing/suit/storage/toggle/labcoat/nt = 3,
		/obj/item/clothing/suit/storage/toggle/labcoat/zeng = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zeng/alt = 2,
		/obj/item/clothing/head/bandana/medical = 4,
		/obj/item/clothing/head/beret/medical = 4,
		/obj/item/clothing/head/beret/corporate/pmc/epmc = 4,
		/obj/item/clothing/head/beret/corporate/zeng = 2,
		/obj/item/clothing/head/beret/corporate/zeng/alt = 2,
		/obj/item/clothing/head/softcap/medical = 4,
		/obj/item/clothing/head/softcap/nt = 3,
		/obj/item/clothing/head/softcap/pmc/epmc = 3,
		/obj/item/clothing/head/softcap/zeng = 3,
		/obj/item/clothing/head/wool/nt = 4,
		/obj/item/clothing/head/wool/pmc/alt = 4,
		/obj/item/clothing/head/wool/zeng = 2,
		/obj/item/clothing/head/wool/zeng/alt = 2,
		/obj/item/storage/belt/fannypack = 3,
		/obj/item/clothing/accessory/poncho/roles/medical = 3,
		/obj/item/clothing/shoes/sneakers/black = 4,
		/obj/item/clothing/shoes/sneakers/medsci = 4,
		/obj/item/clothing/shoes/sneakers/medsci/pmc = 2,
		/obj/item/clothing/shoes/sneakers/medsci/zeng = 2,
		/obj/item/storage/backpack/medic = 4,
		/obj/item/storage/backpack/pharmacy = 3,
		/obj/item/storage/backpack/nt = 3,
		/obj/item/storage/backpack/pmcg = 3,
		/obj/item/storage/backpack/zeng = 3,
		/obj/item/storage/backpack/duffel/med = 4,
		/obj/item/storage/backpack/duffel/pharm = 3,
		/obj/item/storage/backpack/duffel/nt = 3,
		/obj/item/storage/backpack/duffel/pmcg = 3,
		/obj/item/storage/backpack/duffel/zeng = 3,
		/obj/item/storage/backpack/cloak/medical = 4,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/storage/backpack/cloak/phalanx = 2
	)
	premium = list(
		/obj/item/toy/figure/chemist = 3
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/cargo_wardrobe
	name = "CargoDrobe"
	desc = "A highly advanced vending machine for buying cargo related clothing for free."
	icon_state = "cargodrobe"
	product_ads = "These shorts are comfy and easy to wear, get yours now!;Extra sweat-wicking power!;Stop browsing, start wearing, you've got deadlines!"
	vend_reply = "Thank you for using the CargoDrobe!"
	products = list(
		/obj/item/clothing/under/rank/hangar_technician = 3,
		/obj/item/clothing/under/rank/hangar_technician/heph = 3,
		/obj/item/clothing/under/rank/hangar_technician/orion = 3,
		/obj/item/clothing/under/rank/miner = 4,
		/obj/item/clothing/under/rank/miner/heph = 4,
		/obj/item/clothing/under/rank/miner/orion = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/cargo = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/heph = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion = 4,
		/obj/item/clothing/suit/storage/toggle/corp/heph = 4,
		/obj/item/clothing/suit/storage/toggle/corp/orion = 4,
		/obj/item/clothing/suit/storage/toggle/highvis = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_alt = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_orange = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_red = 3,
		/obj/item/clothing/pants/shorts/khaki = 24,
		/obj/item/clothing/pants/highvis = 3,
		/obj/item/clothing/pants/highvis_alt = 3,
		/obj/item/clothing/pants/highvis_orange = 3,
		/obj/item/clothing/pants/highvis_red = 3,
		/obj/item/clothing/head/bandana/cargo = 3,
		/obj/item/clothing/head/bandana/miner = 4,
		/obj/item/clothing/head/beret/cargo = 3,
		/obj/item/clothing/head/beret/corporate/heph = 3,
		/obj/item/clothing/head/beret/corporate/orion = 3,
		/obj/item/clothing/head/softcap/cargo = 3,
		/obj/item/clothing/head/softcap/orion = 3,
		/obj/item/clothing/head/wool/heph = 4,
		/obj/item/clothing/head/wool/orion = 4,
		/obj/item/clothing/head/hardhat/orange = 4,
		/obj/item/clothing/accessory/poncho/roles/cargo = 4,
		/obj/item/clothing/accessory/storage/overalls/mining = 4,
		/obj/item/clothing/glasses/safety/goggles = 3,
		/obj/item/clothing/gloves/black = 3,
		/obj/item/clothing/gloves/yellow = 3,
		/obj/item/clothing/gloves/yellow/specialu = 3,
		/obj/item/clothing/gloves/yellow/specialt = 3,
		/obj/item/clothing/shoes/sneakers/black = 8,
		/obj/item/clothing/shoes/workboots/dark = 8,
		/obj/item/clothing/shoes/workboots/toeless = 4,
		/obj/item/storage/backpack/heph = 4,
		/obj/item/storage/backpack/orion = 4,
		/obj/item/storage/backpack/duffel/heph = 4,
		/obj/item/storage/backpack/duffel/orion = 4,
		/obj/item/storage/backpack/cloak/heph = 2,
		/obj/item/storage/backpack/cloak/orion = 2,
		/obj/item/device/flashlight/marshallingwand = 3
	)
	premium = list(
		/obj/item/toy/figure/cargotech = 3,
		/obj/item/toy/figure/miner = 3
	)
	light_color = COLOR_GOLD

/obj/machinery/vending/wardrobe/robo_wardrobe
	name = "RoboDrobe"
	desc = "A vending machine designed to dispense clothing known only to roboticists."
	icon_state = "robodrobe"
	product_ads = "You turn me TRUE, use defines!;0110001101101100011011100101011001100101;Become 83% less likely to die in The Uprising!"
	vend_reply = "Thank you for using the RoboDrobe!"
	products = list(
		/obj/item/clothing/under/rank/machinist = 3,
		/obj/item/clothing/under/rank/machinist/orion = 2,
		/obj/item/clothing/under/rank/machinist/heph = 2,
		/obj/item/clothing/suit/storage/machinist = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/cargo = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/heph = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/orion = 4,
		/obj/item/clothing/suit/storage/toggle/corp/heph = 4,
		/obj/item/clothing/suit/storage/toggle/corp/orion = 4,
		/obj/item/clothing/suit/storage/toggle/highvis = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_alt = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_orange = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_red = 3,
		/obj/item/clothing/suit/storage/toggle/labcoat = 3,
		/obj/item/clothing/suit/storage/toggle/labcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/orion = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/orion = 2,
		/obj/item/clothing/pants/highvis = 3,
		/obj/item/clothing/pants/highvis_alt = 3,
		/obj/item/clothing/pants/highvis_orange = 3,
		/obj/item/clothing/pants/highvis_red = 3,
		/obj/item/clothing/head/bandana/cargo = 3,
		/obj/item/clothing/head/beret/cargo = 3,
		/obj/item/clothing/head/beret/corporate/heph = 3,
		/obj/item/clothing/head/beret/corporate/orion = 3,
		/obj/item/clothing/head/softcap/cargo = 3,
		/obj/item/clothing/head/softcap/orion = 3,
		/obj/item/clothing/head/wool/heph = 4,
		/obj/item/clothing/head/wool/orion = 4,
		/obj/item/clothing/accessory/poncho/roles/cargo = 4,
		/obj/item/clothing/glasses/safety/goggles = 3,
		/obj/item/clothing/gloves/black = 3,
		/obj/item/clothing/gloves/yellow = 3,
		/obj/item/clothing/gloves/yellow/specialu = 3,
		/obj/item/clothing/gloves/yellow/specialt = 3,
		/obj/item/clothing/shoes/sneakers/black = 3,
		/obj/item/clothing/shoes/workboots/dark = 4,
		/obj/item/clothing/shoes/workboots/toeless = 2,
		/obj/item/storage/backpack/heph = 4,
		/obj/item/storage/backpack/orion = 4,
		/obj/item/storage/backpack/duffel/heph = 4,
		/obj/item/storage/backpack/duffel/orion = 4,
		/obj/item/storage/backpack/cloak/cargo = 3,
		/obj/item/storage/backpack/cloak/heph = 2,
		/obj/item/storage/backpack/cloak/orion = 2
	)
	premium = list(
		/obj/item/toy/figure/roboticist = 3,
		/obj/item/toy/figure/borg = 3
	)
	light_color = COLOR_LIME
