/**
 * Drobes
 */


/obj/machinery/vending/wardrobe
	name = "Drobe - PARENT DO NOT USE"
	random_itemcount = FALSE

/obj/machinery/vending/wardrobe/engi_wardrobe
	name = "\improper EngiDrobe"
	desc = "A vending machine renowned for vending industrial grade clothing."
	icon_state = "engidrobe"
	light_mask = "clothes_lightmask"
	product_ads = "Guaranteed* to protect against industrial accidents! (*not guaranteed);Yellow is the most radiation-resistant color!;Hi-viz is in this year! No, really!;You're the smartest department on the ship, so dress like it!"
	vend_reply = "Thank you for using EngiDrobe!"
	products = list(
		/obj/item/clothing/under/rank/engineer/apprentice/heph = 2,
		/obj/item/clothing/under/rank/engineer/apprentice/zavod = 2,
		/obj/item/clothing/under/rank/engineer/heph = 4,
		/obj/item/clothing/under/rank/engineer/zavod = 4,
		/obj/item/clothing/suit/storage/hazardvest = 5,
		/obj/item/clothing/suit/storage/hazardvest/green = 2,
		/obj/item/clothing/suit/storage/hazardvest/red = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/engineering = 8,
		/obj/item/clothing/suit/storage/hooded/wintercoat/heph = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/engi_dep_jacket = 8,
		/obj/item/clothing/suit/storage/toggle/corp/heph = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/highvis = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_alt = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_orange = 5,
		/obj/item/clothing/suit/storage/toggle/highvis_red = 5,
		/obj/item/clothing/suit/storage/toggle/labcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/heph/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/letterman/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/zavodskoi = 2,
		/obj/item/clothing/accessory/poncho/roles/cloak/engineer = 5,
		/obj/item/clothing/glasses/safety/goggles = 6,
		/obj/item/clothing/head/bandana/engineering = 4,
		/obj/item/clothing/head/beret/engineering = 4,
		/obj/item/clothing/head/beret/corporate/heph = 3,
		/obj/item/clothing/head/beret/corporate/zavod = 2,
		/obj/item/clothing/head/beret/corporate/zavod/alt = 2,
		/obj/item/clothing/head/hardhat/green = 2,
		/obj/item/clothing/head/hardhat/orange = 4,
		/obj/item/clothing/head/hardhat/red = 2,
		/obj/item/clothing/head/sidecap/zavod = 3,
		/obj/item/clothing/head/sidecap/zavod/alt = 3,
		/obj/item/clothing/head/softcap/engineering = 4,
		/obj/item/clothing/head/softcap/zavod = 2,
		/obj/item/clothing/head/softcap/zavod/alt = 2,
		/obj/item/clothing/head/wool/heph = 4,
		/obj/item/clothing/head/wool/zavod = 2,
		/obj/item/clothing/head/wool/zavod/alt = 2,
		/obj/item/clothing/pants/highvis = 5,
		/obj/item/clothing/pants/highvis_alt = 5,
		/obj/item/clothing/pants/highvis_orange = 5,
		/obj/item/clothing/pants/highvis_red = 5,
		/obj/item/clothing/shoes/sneakers/orange = 6,
		/obj/item/clothing/shoes/workboots/dark = 6,
		/obj/item/clothing/shoes/workboots/toeless = 4,
		/obj/item/storage/backpack/industrial = 6,
		/obj/item/storage/backpack/heph = 4,
		/obj/item/storage/backpack/zavod = 4,
		/obj/item/storage/backpack/duffel/eng = 6,
		/obj/item/storage/backpack/duffel/heph = 4,
		/obj/item/storage/backpack/duffel/zavod = 4,
		/obj/item/storage/backpack/cloak/engi = 3,
		/obj/item/storage/backpack/cloak/heph = 2,
		/obj/item/storage/backpack/cloak/zavod = 2
	)
	contraband = list(
		/obj/item/clothing/under/rank/engineer/einstein = 4
	)
	light_color = COLOR_GOLD

/obj/machinery/vending/wardrobe/atmos_wardrobe
	name = "\improper AtmosDrobe"
	desc = "This relatively unknown vending machine delivers clothing for Atmospherics Technicians, an equally unknown job."
	icon_state = "atmosdrobe"
	light_mask = "clothes_lightmask"
	product_ads = "Flammable? Inflammable? Doesn't matter!;If you know the Ideal Gas constant, show it off with these clothes!;Show up those pitiful engineers with stylish blue trim today!;Long live Atmosia! Gloria Admosia!"
	vend_reply = "Thank you for using Atmosdrobe!"
	products = list(
		/obj/item/clothing/under/rank/atmospheric_technician/heph = 2,
		/obj/item/clothing/under/rank/atmospheric_technician/zavod = 2,
		/obj/item/clothing/suit/storage/hazardvest/blue/atmos = 3,
		/obj/item/clothing/suit/storage/hazardvest/green = 2,
		/obj/item/clothing/suit/storage/hazardvest/red = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/engineering/atmos = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/heph = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/engi_dep_jacket = 4,
		/obj/item/clothing/suit/storage/toggle/corp/heph = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/highvis = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_alt = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_orange = 3,
		/obj/item/clothing/suit/storage/toggle/highvis_red = 3,
		/obj/item/clothing/suit/storage/toggle/labcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/heph/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/letterman/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/heph = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/zavodskoi = 2,
		/obj/item/clothing/accessory/poncho/roles/cloak/atmos = 3,
		/obj/item/clothing/pants/highvis = 3,
		/obj/item/clothing/pants/highvis_alt = 3,
		/obj/item/clothing/pants/highvis_orange = 3,
		/obj/item/clothing/pants/highvis_red = 3,
		/obj/item/clothing/glasses/safety/goggles = 3,
		/obj/item/clothing/head/bandana/atmos = 2,
		/obj/item/clothing/head/beret/atmos = 2,
		/obj/item/clothing/head/beret/corporate/heph = 3,
		/obj/item/clothing/head/beret/corporate/zavod = 2,
		/obj/item/clothing/head/beret/corporate/zavod/alt = 2,
		/obj/item/clothing/head/hardhat/orange = 2,
		/obj/item/clothing/head/hardhat/green = 2,
		/obj/item/clothing/head/hardhat/red = 2,
		/obj/item/clothing/head/sidecap/zavod = 3,
		/obj/item/clothing/head/sidecap/zavod/alt = 3,
		/obj/item/clothing/head/softcap/atmos = 2,
		/obj/item/clothing/head/softcap/zavod = 2,
		/obj/item/clothing/head/softcap/zavod/alt = 2,
		/obj/item/clothing/head/wool/heph = 4,
		/obj/item/clothing/head/wool/zavod = 2,
		/obj/item/clothing/head/wool/zavod/alt = 2,
		/obj/item/clothing/shoes/sneakers/orange = 4,
		/obj/item/clothing/shoes/workboots/dark = 4,
		/obj/item/clothing/shoes/workboots/toeless = 2,
		/obj/item/storage/backpack/industrial = 6,
		/obj/item/storage/backpack/heph = 4,
		/obj/item/storage/backpack/zavod = 4,
		/obj/item/storage/backpack/duffel/eng = 6,
		/obj/item/storage/backpack/duffel/heph = 4,
		/obj/item/storage/backpack/duffel/zavod = 4,
		/obj/item/storage/backpack/cloak/engi = 3,
		/obj/item/storage/backpack/cloak/heph = 2,
		/obj/item/storage/backpack/cloak/zavod = 2
	)
	contraband = list(
		/obj/item/clothing/under/rank/engineer/einstein = 4
	)
	light_color = COLOR_GOLD

/obj/machinery/vending/wardrobe/sec_wardrobe
	name = "\improper SecDrobe"
	desc = "A vending machine for security and security-related clothing!"
	icon_state = "secdrobe"
	light_mask = "clothes_lightmask"
	product_ads = "Beat perps in style!;You have the right to be fashionable!;Now you can be the fashion police you always wanted to be!;Blood on your uniform? Don't wash it out, get a new one!;Be more than a mall cop!"
	vend_reply = "Thank you for using SecDrobe!"
	products = list(
		/obj/item/clothing/under/rank/cadet = 4,
		/obj/item/clothing/under/rank/cadet/idris = 3,
		/obj/item/clothing/under/rank/cadet/pmc = 3,
		/obj/item/clothing/under/rank/cadet/zavod = 3,
		/obj/item/clothing/under/rank/security = 4,
		/obj/item/clothing/under/rank/security/idris = 3,
		/obj/item/clothing/under/rank/security/idris/idrissec = 3,
		/obj/item/clothing/under/rank/security/idris/idrissec/alt = 3,
		/obj/item/clothing/under/rank/security/pmc = 3,
		/obj/item/clothing/under/rank/security/pmc/pmcsec = 3,
		/obj/item/clothing/under/rank/security/pmc/pmcsec/alt = 3,
		/obj/item/clothing/under/rank/security/zavod = 3,
		/obj/item/clothing/under/rank/security/zavod/zavodsec = 3,
		/obj/item/clothing/under/rank/security/zavod/zavodsec/alt = 3,
		/obj/item/clothing/under/det = 2,
		/obj/item/clothing/under/det/idris = 2,
		/obj/item/clothing/under/det/idris/alt = 2,
		/obj/item/clothing/under/det/pmc = 2,
		/obj/item/clothing/under/det/pmc/alt = 2,
		/obj/item/clothing/under/det/zavod = 2,
		/obj/item/clothing/under/det/zavod/alt = 2,
		/obj/item/clothing/under/rank/warden = 2,
		/obj/item/clothing/under/rank/warden/idris = 2,
		/obj/item/clothing/under/rank/warden/pmc = 2,
		/obj/item/clothing/under/rank/warden/zavod = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/security = 8,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/pmc = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod = 4,
		/obj/item/clothing/suit/storage/hooded/wintercoat/zavod/alt = 4,
		/obj/item/clothing/suit/storage/security/officer/idris = 2,
		/obj/item/clothing/suit/storage/security/officer/idris/alt = 2,
		/obj/item/clothing/suit/storage/security/officer/pmc = 4,
		/obj/item/clothing/suit/storage/security/officer/zav = 2,
		/obj/item/clothing/suit/storage/security/officer/zav/alt = 2,
		/obj/item/clothing/suit/storage/security/investigator = 2,
		/obj/item/clothing/suit/storage/security/investigator/idris = 2,
		/obj/item/clothing/suit/storage/security/investigator/pmc = 2,
		/obj/item/clothing/suit/storage/security/investigator/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/warden = 2,
		/obj/item/clothing/suit/storage/toggle/warden/idris = 2,
		/obj/item/clothing/suit/storage/toggle/warden/pmc = 2,
		/obj/item/clothing/suit/storage/toggle/warden/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/warden/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/idris = 2,
		/obj/item/clothing/suit/storage/toggle/corp/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/corp/pmc = 4,
		/obj/item/clothing/suit/storage/toggle/corp/zavod = 2,
		/obj/item/clothing/suit/storage/toggle/corp/zavod/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/alt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman/alt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/pmc = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/pmc/alt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/alt = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/letterman = 4,
		/obj/item/clothing/suit/storage/toggle/labcoat/zavodskoi/letterman/alt = 4,
		/obj/item/clothing/suit/storage/toggle/longcoat/idris = 4,
		/obj/item/clothing/suit/storage/toggle/longcoat/pmc = 4,
		/obj/item/clothing/suit/storage/toggle/longcoat/zavodskoi = 4,
		/obj/item/clothing/suit/storage/toggle/sec_dep_jacket = 8,
		/obj/item/clothing/accessory/holster/waist = 8,
		/obj/item/clothing/accessory/poncho/roles/cloak/security = 8,
		/obj/item/clothing/gloves/black_leather = 8,
		/obj/item/clothing/mask/balaclava = 4,
		/obj/item/clothing/head/bandana/security = 8,
		/obj/item/clothing/head/beret/security = 4,
		/obj/item/clothing/head/beret/security/officer = 4,
		/obj/item/clothing/head/beret/corporate/idris = 4,
		/obj/item/clothing/head/beret/corporate/idris/alt = 4,
		/obj/item/clothing/head/beret/corporate/zavod = 4,
		/obj/item/clothing/head/beret/corporate/zavod/alt = 4,
		/obj/item/clothing/head/peaked_cap/idris = 4,
		/obj/item/clothing/head/peaked_cap/idris/no_logo = 4,
		/obj/item/clothing/head/sidecap/pmcg = 4,
		/obj/item/clothing/head/sidecap/zavod = 4,
		/obj/item/clothing/head/sidecap/zavod/alt = 4,
		/obj/item/clothing/head/softcap/security = 8,
		/obj/item/clothing/head/softcap/idris = 4,
		/obj/item/clothing/head/softcap/idris/alt = 4,
		/obj/item/clothing/head/softcap/pmc = 4,
		/obj/item/clothing/head/softcap/zavod = 4,
		/obj/item/clothing/head/softcap/zavod/alt = 4,
		/obj/item/clothing/head/warden = 2,
		/obj/item/clothing/head/warden/idris = 2,
		/obj/item/clothing/head/warden/pmc = 2,
		/obj/item/clothing/head/warden/zavod = 2,
		/obj/item/clothing/head/warden/zavod/alt = 2,
		/obj/item/clothing/head/wool/idris = 4,
		/obj/item/clothing/head/wool/idris/alt = 4,
		/obj/item/clothing/head/wool/pmc = 4,
		/obj/item/clothing/head/wool/zavod = 4,
		/obj/item/clothing/head/wool/zavod/alt = 4,
		/obj/item/clothing/shoes/jackboots = 8,
		/obj/item/clothing/shoes/jackboots/toeless = 6,
		/obj/item/storage/backpack/security = 6,
		/obj/item/storage/backpack/idris = 4,
		/obj/item/storage/backpack/pmcg = 4,
		/obj/item/storage/backpack/zavod = 4,
		/obj/item/storage/backpack/duffel/sec = 6,
		/obj/item/storage/backpack/duffel/idris = 4,
		/obj/item/storage/backpack/duffel/pmcg = 4,
		/obj/item/storage/backpack/duffel/zavod = 4,
		/obj/item/storage/backpack/cloak/phalanx = 2,
		/obj/item/storage/backpack/cloak/sec = 2,
		/obj/item/storage/backpack/cloak/zavod = 2
	)
	premium = list(
		/obj/item/clothing/accessory/storage/bayonet = 4
	)
	contraband = list(
		/obj/item/clothing/under/rank/security/einstein = 4
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/bar_wardrobe
	name = "BarDrobe"
	desc = "A stylish vendor to dispense the most stylish bar clothing!"
	icon_state = "bardrobe"
	light_mask = "clothes_lightmask"
	product_ads = "Now 12% more stain-resistant!;Better-dressed bartenders get better tips! Hint hint!;Let's class this joint up! Or down, your call!;How's it feel to be the coolest part of the Service department?"
	vend_reply = "Thank you for using the BarDrobe!"
	products = list(
		/obj/item/clothing/under/suit_jacket = 3,
		/obj/item/clothing/under/suit_jacket/really_black = 3,
		/obj/item/clothing/under/suit_jacket/red = 3,
		/obj/item/clothing/under/suit_jacket/navy = 3,
		/obj/item/clothing/under/suit_jacket/burgundy = 3,
		/obj/item/clothing/under/sl_suit = 3,
		/obj/item/clothing/suit/storage/bartender = 3,
		/obj/item/clothing/head/bowler = 3,
		/obj/item/clothing/head/that = 3,
		/obj/item/clothing/head/pin/flower = 3,
		/obj/item/clothing/head/pin/flower/pink = 3,
		/obj/item/clothing/head/pin/flower/yellow = 3,
		/obj/item/clothing/head/pin/flower/blue = 3,
		/obj/item/clothing/head/pin/magnetic = 3,
		/obj/item/clothing/head/flatcap/bartender = 3,
		/obj/item/clothing/accessory/wcoat = 3,
		/obj/item/clothing/shoes/sneakers/black = 3,
		/obj/item/clothing/shoes/laceup = 3,
		/obj/item/clothing/shoes/laceup/grey = 3,
		/obj/item/clothing/suit/storage/bartender/idris = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/idris = 2,
		/obj/item/clothing/head/beret/corporate/idris = 3,
		/obj/item/clothing/head/beret/corporate/idris/alt = 3,
		/obj/item/clothing/head/peaked_cap/idris = 3,
		/obj/item/clothing/head/peaked_cap/idris/no_logo = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/clothing/head/flatcap/bartender/idris = 3,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/clothing/under/rank/bartender = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/nt = 2,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/clothing/suit/storage/bartender/orion = 3,
		/obj/item/clothing/head/flatcap/bartender/orion = 3,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
		/obj/item/storage/backpack/cloak/orion = 2,
	)
	premium = list(
		/obj/item/clothing/accessory/storage/bandolier = 2,
		/obj/item/clothing/head/bearpelt = 2,
		/obj/item/clothing/head/cowboy = 2,
		/obj/item/clothing/head/fez = 2,
	)
	contraband = list(
		/obj/item/clothing/head/welding = 2
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/chef_wardrobe
	name = "ChefDrobe"
	desc = "This vending machine might not dispense meat, but it certainly dispenses chef related clothing."
	icon_state = "chefdrobe"
	light_mask = "clothes_lightmask"
	product_ads = "Our clothes are guaranteed to protect you from food splatters!"
	vend_reply = "Thank you for using the ChefDrobe!"
	products = list(
		/obj/item/clothing/under/waiter = 3,
		/obj/item/clothing/under/rank/chef = 3,
		/obj/item/clothing/head/hairnet = 3,
		/obj/item/storage/box/gloves = 3,
		/obj/item/clothing/under/rank/chef/idris = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/idris = 2,
		/obj/item/clothing/head/chefhat/idris = 3,
		/obj/item/clothing/head/beret/corporate/idris = 3,
		/obj/item/clothing/head/beret/corporate/idris/alt = 3,
		/obj/item/clothing/head/peaked_cap/idris = 3,
		/obj/item/clothing/head/peaked_cap/idris/no_logo = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/clothing/head/chefhat/nt = 3,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/clothing/under/rank/chef/orion = 3,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
	)
	light_color = COLOR_PALE_BLUE_GRAY

/obj/machinery/vending/wardrobe/jani_wardrobe
	name = "JaniDrobe"
	desc = "A self-cleaning vending machine capable of dispensing clothing for janitors."
	icon_state = "janidrobe"
	light_mask = "clothes_lightmask"
	product_ads = "Now endorsed by lizard janitors everywhere!;Proudly represent Janitor Nation!;Don't worry, purple is in this season!;Got hydraulic fluid and blood all over your clothes? Get some new ones!"
	vend_reply = "Thank you for using the JaniDrobe!"
	products = list(
		/obj/item/clothing/under/rank/janitor = 3,
		/obj/item/clothing/under/rank/janitor/alt = 3,
		/obj/item/clothing/head/bandana/janitor = 3,
		/obj/item/clothing/head/beret/janitor = 3,
		/obj/item/clothing/head/softcap/nt/custodian = 3,
		/obj/item/clothing/head/softcap/idris/custodian = 3,
		/obj/item/clothing/glasses/safety/goggles = 6,
		/obj/item/clothing/gloves/janitor = 4,
		/obj/item/clothing/gloves/janitor/unathi = 2,
		/obj/item/clothing/gloves/janitor/tajara = 2,
		/obj/item/clothing/gloves/janitor/vaurca = 2,
		/obj/item/storage/belt/custodial = 3,
		/obj/item/clothing/accessory/holster/utility/custodial/hip = 2,
		/obj/item/clothing/accessory/holster/utility/custodial/armpit = 2,
		/obj/item/clothing/shoes/galoshes = 4,
		/obj/item/clothing/suit/caution = 6,
		/obj/item/clothing/under/rank/janitor/idris = 3,
		/obj/item/clothing/under/rank/janitor/idris/alt = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/idris = 2,
		/obj/item/clothing/head/beret/corporate/idris = 3,
		/obj/item/clothing/head/beret/corporate/idris/alt = 3,
		/obj/item/clothing/head/peaked_cap/idris = 3,
		/obj/item/clothing/head/peaked_cap/idris/no_logo = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/clothing/head/chefhat/nt = 3,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/clothing/under/rank/janitor/orion = 3,
		/obj/item/clothing/under/rank/chef/orion = 3,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
		/obj/item/storage/backpack/cloak/orion = 2
	)
	light_color = COLOR_VIOLET

/obj/machinery/vending/wardrobe/hydro_wardrobe
	name = "Hydrobe"
	desc = "A machine with a catchy name. It dispenses botany related clothing and gear."
	icon_state = "hydrobe"
	light_mask = "clothes_lightmask"
	product_ads = "Do you love soil? Then buy our clothes!;Get outfits to match your green thumb here!;Soil resistant! Or absorbant! Who cares!;Guaranteed-ish to make plants grow faster if you wear it!"
	vend_reply = "Thank you for using the Hydrobe!"
	products = list(
		/obj/item/clothing/suit/storage/hooded/wintercoat/hydro = 4,
		/obj/item/clothing/head/bandana/hydro = 3,
		/obj/item/clothing/head/beret/hydro = 3,
		/obj/item/clothing/head/softcap/hydro = 3,
		/obj/item/clothing/gloves/botanic_leather = 4,
		/obj/item/clothing/gloves/botanic_leather/unathi = 2,
		/obj/item/clothing/gloves/botanic_leather/tajara = 2,
		/obj/item/clothing/gloves/botanic_leather/vaurca = 2,
		/obj/item/storage/backpack/hydroponics = 5,
		/obj/item/storage/backpack/duffel/hyd = 5,
		/obj/item/clothing/head/bandana/hydro/idris = 3,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris = 2,
		/obj/item/clothing/suit/storage/hooded/wintercoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/alt = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman = 2,
		/obj/item/clothing/suit/storage/toggle/labcoat/idris/letterman/alt = 2,
		/obj/item/clothing/suit/storage/toggle/longcoat/idris = 2,
		/obj/item/clothing/head/beret/corporate/idris = 3,
		/obj/item/clothing/head/beret/corporate/idris/alt = 3,
		/obj/item/clothing/head/peaked_cap/idris = 3,
		/obj/item/clothing/head/peaked_cap/idris/no_logo = 3,
		/obj/item/clothing/head/softcap/idris = 3,
		/obj/item/clothing/head/softcap/idris/alt = 3,
		/obj/item/storage/backpack/idris = 2,
		/obj/item/storage/backpack/duffel/idris = 2,
		/obj/item/clothing/head/bandana/hydro/nt = 3,
		/obj/item/storage/backpack/nt = 2,
		/obj/item/storage/backpack/duffel/nt = 2,
		/obj/item/storage/backpack/cloak/nt = 2,
		/obj/item/clothing/head/bandana/hydro/orion = 3,
		/obj/item/storage/backpack/orion = 2,
		/obj/item/storage/backpack/duffel/orion = 2,
		/obj/item/storage/backpack/cloak/orion = 2
	)
	light_color = COLOR_LIME
