name: Update TGS DMAPI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-dmapi:
    runs-on: ubuntu-20.04
    name: Update the TGS DMAPI
    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Branch
      run: |
        git branch -f tgs-dmapi-update
        git checkout tgs-dmapi-update
        git reset --hard master

    - name: Apply DMAPI update
      uses: tgstation/tgs-dmapi-updater@v2
      with:
        header-path: 'code/__defines/tgs.dm'
        library-path: 'code/modules/tgs'

    - name: Commit and Push
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "AuroraBuildBot"
        git add .
        git commit -m 'Update TGS DMAPI'
        git push -f -u origin tgs-dmapi-update

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      if: ${{ success() }}
      with:
        source_branch: "tgs-dmapi-update"
        destination_branch: "master"
        pr_title: "Automatic TGS DMAPI Update"
        pr_body: "This pull request updates the TGS DMAPI to the latest version. Please note any changes that may be breaking or unimplemented in your codebase by checking what changes are in the definitions file: code/__DEFINES/tgs.dm before merging."
        pr_label: "Tools"
        pr_allow_empty: false
        github_token: ${{ secrets.BOT_TOKEN_AURORA }}
